/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/order-imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ImportOrders"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo-data/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SeedDemoOrders"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk-evaluations:run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RunScoring"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description One page of alerts. 'severity' filters on the frozen snapshot each alert was opened with, while 'sort=SCORE_DESC' orders by the local score of the evaluation the current run made current: the two describe different moments. An alert with no current evaluation has no score to compare and sorts last. 'scoringRunSequence' identifies the state the page was read from; a client that pages restarts when it changes. */
        get: operations["ListAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAlert"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReviewAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Operational state of the current scoring run. Amounts are reported per currency and never summed across them; reported fraud is aggregated by distinct order. No field is derived from ground-truth labels, which do not exist outside a demo corpus. */
        get: operations["GetDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Quality of the deterministic criterion over the current scoring run, measured against the ground truth of the demo corpus. Orders without a label are counted and excluded, never a reason to fail. */
        get: operations["GetEvaluationMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AlertDetail: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderId: string;
            status: string;
            severity: string;
            alertPolicyVersion: string;
            /** Format: uuid */
            supersedesAlertId: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            reviewedAt: null | string;
            order: components["schemas"]["AlertOrderView"];
            snapshot: components["schemas"]["AlertSnapshotView"];
            currentEvaluation: null | components["schemas"]["AlertEvaluationView"];
            currentRun: null | components["schemas"]["ScoringRunReference"];
            divergence: components["schemas"]["AlertDivergenceView"];
            review: null | components["schemas"]["AlertReviewView"];
        };
        AlertDivergenceView: {
            hasBandDivergence: boolean;
            /** Format: int32 */
            snapshotScore: number | string;
            snapshotSeverity: string;
            /** Format: int32 */
            currentScore: null | number | string;
            currentSeverity: null | string;
        };
        AlertEvaluationView: {
            /** Format: uuid */
            evaluationId: string;
            /** Format: int32 */
            score: number | string;
            severity: null | string;
            isFlagged: boolean;
            signals: components["schemas"]["AlertSignalView"][];
            /** Format: date-time */
            evaluatedAt: string;
        };
        AlertListItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderId: string;
            merchantReferenceId: string;
            buyerReferenceId: string;
            /** Format: date-time */
            occurredAt: string;
            /** Format: int64 */
            amountCents: number | string;
            currencyCode: string;
            countryCode: string;
            status: string;
            severity: string;
            /** Format: int32 */
            riskScoreSnapshot: number | string;
            /** Format: int32 */
            currentRiskScore: null | number | string;
            currentSeverity: null | string;
            hasBandDivergence: boolean;
            alertPolicyVersion: string;
            /** Format: uuid */
            supersedesAlertId: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            reviewedAt: null | string;
        };
        AlertOrderView: {
            /** Format: uuid */
            id: string;
            merchantId: string;
            merchantReferenceId: string;
            buyerReferenceId: string;
            /** Format: date-time */
            occurredAt: string;
            /** Format: int64 */
            amountCents: number | string;
            currencyCode: string;
            countryCode: string;
            city: null | string;
            deviceSessionId: null | string;
        };
        AlertReviewResult: {
            applied: boolean;
            alert: components["schemas"]["AlertDetail"];
        };
        AlertReviewView: {
            /** Format: uuid */
            id: string;
            previousStatus: string;
            newStatus: string;
            note: null | string;
            /** Format: date-time */
            reviewedAt: string;
        };
        AlertSignalView: {
            rule: string;
            /** Format: int32 */
            weight: number | string;
            detail: string;
        };
        AlertSnapshotView: {
            /** Format: uuid */
            evaluationId: string;
            /** Format: int32 */
            score: number | string;
            severity: string;
            signals: components["schemas"]["AlertSignalView"][];
        };
        CapabilitiesResponse: {
            demoDataEnabled: boolean;
        };
        ConfusionMatrixView: {
            /** Format: int32 */
            truePositives: number | string;
            /** Format: int32 */
            falsePositives: number | string;
            /** Format: int32 */
            falseNegatives: number | string;
            /** Format: int32 */
            trueNegatives: number | string;
        };
        DashboardAmountAtRiskView: {
            currencyCode: string;
            /** Format: int64 */
            amountCents: number | string;
            /** Format: int32 */
            alertCount: number | string;
        };
        DashboardOpenAlertsView: {
            /** Format: int32 */
            total: number | string;
            bySeverity: components["schemas"]["DashboardSeverityCountView"][];
        };
        DashboardReportedFraudView: {
            currencyCode: string;
            /** Format: int64 */
            amountCents: number | string;
            /** Format: int32 */
            orderCount: number | string;
        };
        DashboardResult: {
            scoringRun: null | components["schemas"]["DashboardScoringRunView"];
            /** Format: int32 */
            ordersPendingScoring: number | string;
            openAlerts: components["schemas"]["DashboardOpenAlertsView"];
            amountAtRisk: components["schemas"]["DashboardAmountAtRiskView"][];
            reportedFraud: components["schemas"]["DashboardReportedFraudView"][];
            /** Format: double */
            flagRate: null | number | string;
            riskOverTime: components["schemas"]["DashboardRiskBucketView"][];
            topSignals: components["schemas"]["DashboardSignalView"][];
        };
        DashboardRiskBucketView: {
            /** Format: date */
            weekStart: string;
            /** Format: int32 */
            orderCount: number | string;
            /** Format: int32 */
            flaggedCount: number | string;
        };
        DashboardScoringRunView: {
            /** Format: int64 */
            sequence: number | string;
            /** Format: date-time */
            completedAt: string;
            /** Format: int32 */
            orderCount: number | string;
        };
        DashboardSeverityCountView: {
            severity: string;
            /** Format: int32 */
            alertCount: number | string;
        };
        DashboardSignalView: {
            rule: string;
            /** Format: int32 */
            alertCount: number | string;
        };
        EvaluationMetricsResult: {
            /** Format: int64 */
            scoringRunSequence: number | string;
            /** Format: date-time */
            scoringRunCompletedAt: string;
            ruleConfigVersion: string;
            /** Format: int32 */
            scoredOrders: number | string;
            /** Format: int32 */
            labeledOrders: number | string;
            /** Format: int32 */
            unlabeledOrders: number | string;
            /** Format: int32 */
            calibrationOrders: number | string;
            /** Format: int32 */
            holdoutOrders: number | string;
            calibrationSweep: components["schemas"]["ThresholdMetricsView"][];
            selectedThreshold: components["schemas"]["ThresholdMetricsView"];
            holdout: components["schemas"]["EvaluationMetricsView"];
        };
        EvaluationMetricsView: {
            matrix: components["schemas"]["ConfusionMatrixView"];
            /** Format: double */
            precision: null | number | string;
            /** Format: double */
            recall: null | number | string;
            /** Format: double */
            f1: null | number | string;
            /** Format: double */
            falsePositiveRate: null | number | string;
            /** Format: double */
            flagRate: null | number | string;
        };
        HealthResponse: {
            status: string;
            service: string;
        };
        /** Format: binary */
        IFormFile: string;
        ImportOrdersResult: {
            /** Format: int32 */
            totalRecords: number | string;
            /** Format: int32 */
            importedCount: number | string;
            /** Format: int32 */
            duplicateCount: number | string;
            /** Format: int32 */
            invalidRecordCount: number | string;
            errorsTruncated: boolean;
            errors: components["schemas"]["ImportRecordError"][];
        };
        ImportRecordError: {
            /** Format: int32 */
            recordNumber: number | string;
            /** Format: int32 */
            lineNumber: null | number | string;
            field: null | string;
            code: string;
            message: string;
        };
        ListAlertsResult: {
            items: components["schemas"]["AlertListItem"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int64 */
            scoringRunSequence: null | number | string;
            currentRun: null | components["schemas"]["ScoringRunReference"];
        };
        ListOrdersResult: {
            items: components["schemas"]["OrderListItem"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
        };
        OrderListItem: {
            /** Format: uuid */
            id: string;
            merchantId: string;
            merchantReferenceId: string;
            buyerReferenceId: string;
            /** Format: date-time */
            occurredAt: string;
            /** Format: int64 */
            amountCents: number | string;
            currencyCode: string;
            countryCode: string;
            city: null | string;
            channel: null | string;
            deviceSessionId: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        ReviewAlertRequest: {
            newStatus: null | string;
            note: null | string;
            acknowledgedDivergence: null | boolean;
        };
        ScoringRunReference: {
            /** Format: int64 */
            sequence: number | string;
            /** Format: date-time */
            completedAt: string;
        };
        ScoringRunSummary: {
            /** Format: uuid */
            runId: string;
            /** Format: int64 */
            sequence: number | string;
            ruleConfigVersion: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: string;
            /** Format: int32 */
            orderCount: number | string;
            /** Format: int32 */
            evaluationsCreated: number | string;
            /** Format: int32 */
            evaluationsReused: number | string;
            /** Format: int32 */
            alertsCreated: number | string;
            /** Format: int32 */
            alertsSkippedOpen: number | string;
            /** Format: int32 */
            alertsSkippedReviewed: number | string;
        };
        SeedDemoOrdersResult: {
            datasetVersion: string;
            /** Format: int32 */
            totalOrders: number | string;
            /** Format: int32 */
            insertedOrders: number | string;
            /** Format: int32 */
            duplicateOrders: number | string;
            /** Format: int32 */
            totalLabels: number | string;
            /** Format: int32 */
            insertedLabels: number | string;
            /** Format: int32 */
            fraudLabelCount: number | string;
        };
        ThresholdMetricsView: {
            /** Format: int32 */
            threshold: number | string;
            metrics: components["schemas"]["EvaluationMetricsView"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    GetCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    ImportOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["IFormFile"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOrdersResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Payload Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListOrders: {
        parameters: {
            query?: {
                page?: number | string;
                pageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListOrdersResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SeedDemoOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedDemoOrdersResult"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RunScoring: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoringRunSummary"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListAlerts: {
        parameters: {
            query?: {
                status?: string;
                severity?: string;
                sort?: string;
                page?: number | string;
                pageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAlertsResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ReviewAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["ReviewAlertRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertReviewResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResult"];
                };
            };
        };
    };
    GetEvaluationMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationMetricsResult"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
