/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/order-imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ImportOrders"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo-data/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Loads the demo corpus. Idempotent: an order that is already there with the same facts is left alone. It refuses without writing anything when the database holds orders with these merchant references and different facts, and says which of the two causes it is. */
        post: operations["SeedDemoOrders"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo-data/seed-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description What loading the demo corpus would do, without doing it. The console reads it when the import screen opens so that a database holding the previous corpus is announced before the button is pressed rather than discovered by pressing it. It runs the very same comparison the load runs, and writes nothing. */
        get: operations["GetDemoSeedPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk-evaluations:run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RunScoring"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description One page of alerts. 'severity' filters on the frozen snapshot each alert was opened with, while 'sort=SCORE_DESC' orders by the local score of the evaluation the current run made current: the two describe different moments. An alert with no current evaluation has no score to compare and sorts last. 'scoringRunSequence' identifies the state the page was read from; a client that pages restarts when it changes. */
        get: operations["ListAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAlert"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReviewAlert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alertId}/explanation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Explains, in words, the evaluation this alert was opened on. Idempotent: when an explanation already exists the existing one is returned with 'applied' false, so a repeated request neither asks a provider twice nor changes anything. 'regenerate' asks for another attempt, and is allowed only over an explanation that failed and still has attempts left. Every figure of the text is verified against the evaluation before it is stored, so a provider that invents one produces a failed explanation rather than a paragraph: that is a 200 with the row in FAILED, never a server error. There is no separate GET — the alert detail carries the explanation, and the absence of one is an ordinary state rather than a 404. */
        post: operations["RequestAlertExplanation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}/external-evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The external evaluation history of the order, oldest first. An order may accumulate several over time; only one of them is ever waiting for an answer. */
        get: operations["ListOrderExternalEvaluations"];
        put?: never;
        /** @description Asks an external provider to evaluate the order. Idempotent: when the order already has an evaluation the existing one is returned with 'applied' false, so a repeated request neither creates a second evaluation on the provider side nor changes anything here. 'requestNew' asks for another evaluation anyway, and is allowed only when the current one ended in ERROR. A provider failure is not a server error for the console: the row settles in ERROR or stays PENDING and the response is 200 with that row. */
        post: operations["RequestExternalEvaluation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/external-evaluations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetExternalEvaluation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/external-evaluations:reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Asks the provider again about every evaluation still waiting for an answer, and applies whatever it says. Explicit and manual, like the scoring run: this system has no background jobs and no automatic retries. Each evaluation is saved on its own, so one that another writer moved first is reported in 'conflicted' without rolling back the rest. */
        post: operations["ReconcileExternalEvaluations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/external-callbacks/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Receives a callback from an external antifraud provider. Authenticated with a shared secret in the X-Salvo-Callback-Secret header, compared in constant time. With no secret configured every request is refused: an unauthenticated callback endpoint would let anyone settle any evaluation. Unknown fields in the payload are ignored, because a provider adds fields without warning and that must not break reception. A duplicate is answered 200 and never 409, which would invite the provider to retry forever; 202 means the message could not be correlated yet and is a private distinction, since every provider reads any 2xx as delivered. This shared secret is not the mechanism a real integration would use. */
        post: operations["ReceiveExternalCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo-data/external-callbacks:deliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Asks the mock provider what it would say about one pending external evaluation, or about every pending one, and feeds that answer back in as a callback through the same use case an external provider reaches. The caller chooses which evaluation and never what it reports. The provider's instant is the moment the evaluation was requested, so delivering the same one twice produces the same deduplication key and is recognised as the replay it is. */
        post: operations["DeliverExternalCallbacks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo-data/external-evaluations:request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Requests an external evaluation for every order this provider has never been asked about. It covers the orders that never produced an alert, which the alert detail cannot reach, without adding an orders screen. Each order goes through the ordinary request use case, so the reservation, the idempotence and the failure taxonomy are the same ones a single request gets. */
        post: operations["RequestCorpusExternalEvaluations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Operational state of the current scoring run. Amounts are reported per currency and never summed across them; reported fraud is aggregated by distinct order. No field is derived from ground-truth labels, which do not exist outside a demo corpus. */
        get: operations["GetDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluation-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Quality of the deterministic criterion over the current scoring run, measured against the ground truth of the demo corpus. Orders without a label are counted and excluded, never a reason to fail. */
        get: operations["GetEvaluationMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AlertDetail: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderId: string;
            status: string;
            severity: string;
            alertPolicyVersion: string;
            /** Format: uuid */
            supersedesAlertId: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            reviewedAt: null | string;
            order: components["schemas"]["AlertOrderView"];
            snapshot: components["schemas"]["AlertSnapshotView"];
            currentEvaluation: null | components["schemas"]["AlertEvaluationView"];
            currentRun: null | components["schemas"]["ScoringRunReference"];
            divergence: components["schemas"]["AlertDivergenceView"];
            externalEvaluation: null | components["schemas"]["AlertExternalEvaluationView"];
            explanation: null | components["schemas"]["AlertExplanationView"];
            currentExplanation: null | components["schemas"]["AlertExplanationView"];
            review: null | components["schemas"]["AlertReviewView"];
        };
        AlertDivergenceView: {
            hasBandDivergence: boolean;
            /** Format: int32 */
            snapshotScore: number | string;
            snapshotSeverity: string;
            /** Format: int32 */
            currentScore: null | number | string;
            currentSeverity: null | string;
        };
        AlertEvaluationView: {
            /** Format: uuid */
            evaluationId: string;
            /** Format: int32 */
            score: number | string;
            severity: null | string;
            isFlagged: boolean;
            signals: components["schemas"]["AlertSignalView"][];
            /** Format: date-time */
            evaluatedAt: string;
        };
        AlertExplanationView: {
            /** Format: uuid */
            id: string;
            provider: string;
            templateVersion: string;
            providerVersion: null | string;
            status: string;
            summary: null | string;
            referencedRules: string[];
            failureCode: null | string;
            /** Format: int32 */
            attemptCount: number | string;
            attemptsExhausted: boolean;
            isOutdated: boolean;
            writtenByAnotherTemplate: boolean;
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            settledAt: null | string;
        };
        AlertExternalEvaluationView: {
            /** Format: uuid */
            id: string;
            provider: string;
            status: string;
            /** Format: int32 */
            score: null | number | string;
            errorCode: null | string;
            lastErrorCode: null | string;
            settledBy: null | string;
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            settledAt: null | string;
            hasContradictoryCallback: boolean;
        };
        AlertListItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderId: string;
            merchantReferenceId: string;
            buyerReferenceId: string;
            /** Format: date-time */
            occurredAt: string;
            /** Format: int64 */
            amountCents: number | string;
            currencyCode: string;
            countryCode: string;
            status: string;
            severity: string;
            /** Format: int32 */
            riskScoreSnapshot: number | string;
            /** Format: int32 */
            currentRiskScore: null | number | string;
            currentSeverity: null | string;
            hasBandDivergence: boolean;
            alertPolicyVersion: string;
            /** Format: uuid */
            supersedesAlertId: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            reviewedAt: null | string;
        };
        AlertOrderView: {
            /** Format: uuid */
            id: string;
            merchantId: string;
            merchantReferenceId: string;
            buyerReferenceId: string;
            /** Format: date-time */
            occurredAt: string;
            /** Format: int64 */
            amountCents: number | string;
            currencyCode: string;
            countryCode: string;
            city: null | string;
            deviceSessionId: null | string;
        };
        AlertReviewResult: {
            applied: boolean;
            alert: components["schemas"]["AlertDetail"];
        };
        AlertReviewView: {
            /** Format: uuid */
            id: string;
            previousStatus: string;
            newStatus: string;
            note: null | string;
            /** Format: uuid */
            explanationId: null | string;
            /** Format: date-time */
            reviewedAt: string;
        };
        AlertSignalView: {
            rule: string;
            /** Format: int32 */
            weight: number | string;
            /** Format: int64 */
            amountCents: null | number | string;
            currencyCode: null | string;
            /** Format: double */
            ratio: null | number | string;
            scope: null | string;
            /** Format: int64 */
            medianCents: null | number | string;
            /** Format: int32 */
            historyCount: null | number | string;
            /** Format: int32 */
            windowDays: null | number | string;
            /** Format: int32 */
            orderCount: null | number | string;
            /** Format: int32 */
            windowMinutes: null | number | string;
            /** Format: int32 */
            threshold: null | number | string;
            fromCountry: null | string;
            toCountry: null | string;
            /** Format: double */
            elapsedMinutes: null | number | string;
            /** Format: int32 */
            bucketStartHour: null | number | string;
            /** Format: int32 */
            bucketEndHour: null | number | string;
            timeZoneId: null | string;
            /** Format: int32 */
            observedCount: null | number | string;
            /** Format: int32 */
            totalCount: null | number | string;
            /** Format: double */
            sharePercent: null | number | string;
            country: null | string;
            habitualCountry: null | string;
            detail: null | string;
        };
        AlertSnapshotView: {
            /** Format: uuid */
            evaluationId: string;
            /** Format: int32 */
            score: number | string;
            severity: string;
            signals: components["schemas"]["AlertSignalView"][];
        };
        CallbackDeliverySummary: {
            /** Format: int32 */
            examined: number | string;
            /** Format: int32 */
            delivered: number | string;
            /** Format: int32 */
            settled: number | string;
            /** Format: int32 */
            replayed: number | string;
            /** Format: int32 */
            unavailable: number | string;
        };
        CapabilitiesResponse: {
            demoDataEnabled: boolean;
            demoSeedEnabled: boolean;
            externalCallbackTriggerEnabled: boolean;
            language: string;
        };
        ConfusionMatrixView: {
            /** Format: int32 */
            truePositives: number | string;
            /** Format: int32 */
            falsePositives: number | string;
            /** Format: int32 */
            falseNegatives: number | string;
            /** Format: int32 */
            trueNegatives: number | string;
        };
        CorpusExternalEvaluationSummary: {
            /** Format: int32 */
            examined: number | string;
            /** Format: int32 */
            requested: number | string;
            /** Format: int32 */
            settled: number | string;
            /** Format: int32 */
            stillPending: number | string;
            /** Format: int32 */
            skipped: number | string;
        };
        DashboardAmountAtRiskView: {
            currencyCode: string;
            /** Format: int64 */
            amountCents: number | string;
            /** Format: int32 */
            alertCount: number | string;
        };
        DashboardExternalDenialsView: {
            /** Format: int32 */
            total: number | string;
            /** Format: int32 */
            listed: number | string;
            items: components["schemas"]["DashboardExternalDenialView"][];
        };
        DashboardExternalDenialView: {
            merchantReferenceId: string;
            /** Format: date-time */
            occurredAt: string;
            /** Format: int64 */
            amountCents: number | string;
            currencyCode: string;
            countryCode: string;
            /** Format: int32 */
            localRiskScore: null | number | string;
        };
        DashboardOpenAlertsView: {
            /** Format: int32 */
            total: number | string;
            bySeverity: components["schemas"]["DashboardSeverityCountView"][];
        };
        DashboardReportedFraudView: {
            currencyCode: string;
            /** Format: int64 */
            amountCents: number | string;
            /** Format: int32 */
            orderCount: number | string;
        };
        DashboardResult: {
            scoringRun: null | components["schemas"]["DashboardScoringRunView"];
            /** Format: int32 */
            ordersPendingScoring: number | string;
            openAlerts: components["schemas"]["DashboardOpenAlertsView"];
            amountAtRisk: components["schemas"]["DashboardAmountAtRiskView"][];
            reportedFraud: components["schemas"]["DashboardReportedFraudView"][];
            /** Format: double */
            flagRate: null | number | string;
            riskOverTime: components["schemas"]["DashboardRiskBucketView"][];
            topSignals: components["schemas"]["DashboardSignalView"][];
            externalDenialsWithoutAlert: components["schemas"]["DashboardExternalDenialsView"];
        };
        DashboardRiskBucketView: {
            /** Format: date */
            weekStart: string;
            /** Format: int32 */
            orderCount: number | string;
            /** Format: int32 */
            flaggedCount: number | string;
        };
        DashboardScoringRunView: {
            /** Format: int64 */
            sequence: number | string;
            /** Format: date-time */
            completedAt: string;
            /** Format: int32 */
            orderCount: number | string;
        };
        DashboardSeverityCountView: {
            severity: string;
            /** Format: int32 */
            alertCount: number | string;
        };
        DashboardSignalView: {
            rule: string;
            /** Format: int32 */
            alertCount: number | string;
        };
        DeliverExternalCallbacksRequest: {
            /** Format: uuid */
            externalEvaluationId: null | string;
        };
        DemoSeedPreviewResult: {
            datasetVersion: string;
            /** Format: int32 */
            totalOrders: number | string;
            /** Format: int32 */
            ordersToInsert: number | string;
            /** Format: int32 */
            duplicateOrders: number | string;
            /** Format: int32 */
            labelsToInsert: number | string;
            conflict: null | string;
        };
        EvaluationMetricsResult: {
            /** Format: int64 */
            scoringRunSequence: number | string;
            /** Format: date-time */
            scoringRunCompletedAt: string;
            ruleConfigVersion: string;
            /** Format: int32 */
            scoredOrders: number | string;
            /** Format: int32 */
            labeledOrders: number | string;
            /** Format: int32 */
            unlabeledOrders: number | string;
            /** Format: int32 */
            calibrationOrders: number | string;
            /** Format: int32 */
            holdoutOrders: number | string;
            calibrationSweep: components["schemas"]["ThresholdMetricsView"][];
            selectedThreshold: components["schemas"]["ThresholdMetricsView"];
            holdout: components["schemas"]["EvaluationMetricsView"];
        };
        EvaluationMetricsView: {
            matrix: components["schemas"]["ConfusionMatrixView"];
            /** Format: double */
            precision: null | number | string;
            /** Format: double */
            recall: null | number | string;
            /** Format: double */
            f1: null | number | string;
            /** Format: double */
            falsePositiveRate: null | number | string;
            /** Format: double */
            flagRate: null | number | string;
        };
        ExternalCallbackResponse: {
            receiptStatus: string;
            isReplay: boolean;
            /** Format: int32 */
            replayCount: number | string;
            /** Format: uuid */
            externalEvaluationId: null | string;
            evaluationStatus: null | string;
        };
        ExternalEvaluationView: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderId: string;
            provider: string;
            referenceId: string;
            externalEvaluationId: null | string;
            status: string;
            /** Format: int32 */
            score: null | number | string;
            errorCode: null | string;
            lastErrorCode: null | string;
            /** Format: int32 */
            attemptCount: number | string;
            settledBy: null | string;
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            settledAt: null | string;
        };
        HealthResponse: {
            status: string;
            service: string;
        };
        /** Format: binary */
        IFormFile: string;
        ImportOrdersResult: {
            /** Format: int32 */
            totalRecords: number | string;
            /** Format: int32 */
            importedCount: number | string;
            /** Format: int32 */
            duplicateCount: number | string;
            /** Format: int32 */
            invalidRecordCount: number | string;
            errorsTruncated: boolean;
            errors: components["schemas"]["ImportRecordError"][];
        };
        ImportRecordError: {
            /** Format: int32 */
            recordNumber: number | string;
            /** Format: int32 */
            lineNumber: null | number | string;
            field: null | string;
            code: string;
            message: string;
        };
        ListAlertsResult: {
            items: components["schemas"]["AlertListItem"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int64 */
            scoringRunSequence: null | number | string;
            currentRun: null | components["schemas"]["ScoringRunReference"];
        };
        ListOrdersResult: {
            items: components["schemas"]["OrderListItem"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
        };
        OrderExternalEvaluationsResult: {
            /** Format: uuid */
            orderId: string;
            items: components["schemas"]["ExternalEvaluationView"][];
        };
        OrderListItem: {
            /** Format: uuid */
            id: string;
            merchantId: string;
            merchantReferenceId: string;
            buyerReferenceId: string;
            /** Format: date-time */
            occurredAt: string;
            /** Format: int64 */
            amountCents: number | string;
            currencyCode: string;
            countryCode: string;
            city: null | string;
            channel: null | string;
            deviceSessionId: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        ReconciliationSummary: {
            /** Format: int32 */
            examined: number | string;
            /** Format: int32 */
            settled: number | string;
            /** Format: int32 */
            stillPending: number | string;
            /** Format: int32 */
            failed: number | string;
            /** Format: int32 */
            conflicted: number | string;
            /** Format: int32 */
            linked: number | string;
            /** Format: date-time */
            reconciledAt: string;
        };
        RequestExplanationRequest: {
            regenerate: null | boolean;
        };
        RequestExplanationResult: {
            applied: boolean;
            explanation: components["schemas"]["AlertExplanationView"];
        };
        RequestExternalEvaluationRequest: {
            provider: null | string;
            requestNew: null | boolean;
        };
        RequestExternalEvaluationResult: {
            applied: boolean;
            evaluation: components["schemas"]["ExternalEvaluationView"];
        };
        ReviewAlertRequest: {
            newStatus: null | string;
            note: null | string;
            acknowledgedDivergence: null | boolean;
            /** Format: uuid */
            explanationId: null | string;
        };
        ScoringRunReference: {
            /** Format: int64 */
            sequence: number | string;
            /** Format: date-time */
            completedAt: string;
        };
        ScoringRunSummary: {
            /** Format: uuid */
            runId: string;
            /** Format: int64 */
            sequence: number | string;
            ruleConfigVersion: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: string;
            /** Format: int32 */
            orderCount: number | string;
            /** Format: int32 */
            evaluationsCreated: number | string;
            /** Format: int32 */
            evaluationsReused: number | string;
            /** Format: int32 */
            alertsCreated: number | string;
            /** Format: int32 */
            alertsSkippedOpen: number | string;
            /** Format: int32 */
            alertsSkippedReviewed: number | string;
        };
        SeedDemoOrdersResult: {
            datasetVersion: string;
            /** Format: int32 */
            totalOrders: number | string;
            /** Format: int32 */
            insertedOrders: number | string;
            /** Format: int32 */
            duplicateOrders: number | string;
            /** Format: int32 */
            totalLabels: number | string;
            /** Format: int32 */
            insertedLabels: number | string;
            /** Format: int32 */
            fraudLabelCount: number | string;
        };
        ThresholdMetricsView: {
            /** Format: int32 */
            threshold: number | string;
            metrics: components["schemas"]["EvaluationMetricsView"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    GetCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    ImportOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["IFormFile"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOrdersResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Payload Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListOrders: {
        parameters: {
            query?: {
                page?: number | string;
                pageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListOrdersResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    SeedDemoOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedDemoOrdersResult"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetDemoSeedPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoSeedPreviewResult"];
                };
            };
        };
    };
    RunScoring: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoringRunSummary"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListAlerts: {
        parameters: {
            query?: {
                status?: string;
                severity?: string;
                sort?: string;
                page?: number | string;
                pageSize?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAlertsResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ReviewAlert: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["ReviewAlertRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertReviewResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RequestAlertExplanation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alertId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["RequestExplanationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestExplanationResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListOrderExternalEvaluations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderExternalEvaluationsResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RequestExternalEvaluation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["RequestExternalEvaluationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestExternalEvaluationResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetExternalEvaluation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalEvaluationView"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ReconcileExternalEvaluations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationSummary"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ReceiveExternalCallback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalCallbackResponse"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalCallbackResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Payload Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    DeliverExternalCallbacks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["DeliverExternalCallbacksRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallbackDeliverySummary"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RequestCorpusExternalEvaluations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusExternalEvaluationSummary"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResult"];
                };
            };
        };
    };
    GetEvaluationMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationMetricsResult"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
