using System.Globalization;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Salvo.Infrastructure.Persistence;
using Salvo.Infrastructure.Persistence.CompiledModels;

namespace Salvo.Api.IntegrationTests;

/// <summary>
/// The compiled model still describes what the configurations describe.
/// </summary>
/// <remarks>
/// <para>
/// <strong>Why this test has to exist.</strong> The application reads its model from
/// <c>Persistence/CompiledModels/</c> so that it does not have to build one by reflection on every
/// cold start — 23,2 of the 77,5 seconds measured in <c>E10A</c>. That file is generated by
/// <c>dotnet ef dbcontext optimize</c> and committed, so it is a second copy of a truth that lives
/// in the configurations. A second copy goes stale, and this one goes stale <em>quietly</em>: EF
/// Core does not compare them at startup. A column renamed in a configuration and not regenerated
/// here would leave the application reading and writing the old name with everything green.
/// </para>
/// <para>
/// <strong>What it does not protect against, said plainly.</strong> The gate already runs
/// <c>dotnet ef migrations has-pending-model-changes</c>, and that check is honest with the compiled
/// model present: the design-time tools build the model from the configurations regardless. So a
/// model change without a migration is already caught. The gap this test closes is the next step
/// along: the migration was added, the schema is right, and only the compiled copy was forgotten.
/// </para>
/// <para>
/// <strong>Why a projection and not <c>ToDebugString</c>.</strong> The two models are different
/// implementations — one a <c>RuntimeModel</c> read from generated code, the other built by the
/// convention pipeline — and their debug strings differ in annotations that say nothing about how
/// an entity is stored. What is compared here is what the store actually sees: tables, columns and
/// their types and nullability, keys, indexes and foreign keys. A difference in any of those is a
/// difference in behaviour.
/// </para>
/// </remarks>
public sealed class CompiledModelIsCurrentTests
{
    [Fact]
    public void TheCompiledModelDescribesTheSameStoreAsTheConfigurations()
    {
        var compiled = Describe(Build(SalvoDbContextModel.Instance));
        var fromConfigurations = Describe(Build(model: null));

        // Named rather than compared as a whole first, because "one line differs somewhere in nine
        // hundred" is not a diagnosis. Entity sets diverge when an entity is added or removed, and
        // that is the difference worth naming on its own.
        Assert.Equal(fromConfigurations.Keys.Order(), compiled.Keys.Order());

        foreach (var (entity, expected) in fromConfigurations)
        {
            Assert.Equal(expected, compiled[entity]);
        }
    }

    /// <summary>
    /// One of the two models, taken through a context so that the provider resolves its type
    /// mappings. Passing <see langword="null"/> builds the one the configurations describe.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Both sides go through a context on purpose. <c>SalvoDbContextModel.Instance</c> on its own is
    /// a model whose runtime dependencies were never initialised, so asking it for a column type
    /// throws; and reading it the way the application reads it is the more faithful comparison
    /// anyway.
    /// </para>
    /// <para>
    /// Constructing the context directly is also what makes the comparison possible at all:
    /// <c>AddInfrastructure</c> asks for the compiled model by name, so a context resolved from the
    /// container would hand back the very thing under test. The assembly attribute the generator
    /// writes is excluded from compilation for this reason, and <c>Salvo.Infrastructure.csproj</c>
    /// says so — with it, no code path in the process could reach the convention-built model.
    /// </para>
    /// </remarks>
    private static IModel Build(IModel? model)
    {
        var builder = new DbContextOptionsBuilder<SalvoDbContext>();

        if (model is not null)
        {
            builder.UseModel(model);
        }

        using var context = new SalvoDbContext(builder.UseSqlite("Data Source=:memory:").Options);

        return context.Model;
    }

    /// <summary>
    /// One entity type as the store sees it: its table, its columns, its keys and its indexes.
    /// </summary>
    private static Dictionary<string, List<string>> Describe(IModel model)
    {
        var described = new Dictionary<string, List<string>>(StringComparer.Ordinal);

        foreach (var entityType in model.GetEntityTypes())
        {
            var lines = new List<string>
            {
                $"table {entityType.GetSchemaQualifiedTableName()}",
            };

            foreach (var property in entityType.GetProperties().OrderBy(p => p.Name, StringComparer.Ordinal))
            {
                var storeObject = StoreObjectIdentifier.Create(entityType, StoreObjectType.Table);
                var columnName = storeObject is { } identifier
                    ? property.GetColumnName(identifier)
                    : property.GetColumnName();

                lines.Add(
                    $"column {property.Name} -> {columnName} "
                    + $"{property.GetColumnType()} "
                    + $"nullable={property.IsNullable} "
                    + $"maxLength={property.GetMaxLength()?.ToString(CultureInfo.InvariantCulture) ?? "-"} "
                    + $"converter={property.GetValueConverter()?.GetType().Name ?? "-"}");
            }

            foreach (var key in entityType.GetKeys())
            {
                lines.Add(
                    $"key primary={key.IsPrimaryKey()} "
                    + $"({string.Join(", ", key.Properties.Select(p => p.Name))})");
            }

            foreach (var index in entityType.GetIndexes())
            {
                lines.Add(
                    $"index {index.GetDatabaseName()} unique={index.IsUnique} "
                    + $"filter={index.GetFilter() ?? "-"} "
                    + $"({string.Join(", ", index.Properties.Select(p => p.Name))})");
            }

            foreach (var foreignKey in entityType.GetForeignKeys())
            {
                lines.Add(
                    $"foreignKey -> {foreignKey.PrincipalEntityType.Name} "
                    + $"delete={foreignKey.DeleteBehavior} "
                    + $"({string.Join(", ", foreignKey.Properties.Select(p => p.Name))})");
            }

            lines.Sort(StringComparer.Ordinal);
            described[entityType.Name] = lines;
        }

        return described;
    }
}
