using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Salvo.Application.Risk;
using Salvo.Domain.Explanations;
using Salvo.Domain.Orders;
using Salvo.Domain.Risk;
using Salvo.Infrastructure.Persistence;

namespace Salvo.Api.IntegrationTests;

/// <summary>
/// The typed fields of every signal the demo corpus raises, pinned to a file.
/// </summary>
/// <remarks>
/// <para>
/// <strong>This is the oracle of <c>E9B</c>, and it only works because it was captured first.</strong>
/// The engine writes each signal as an English sentence, and <see cref="SignalFacts"/> exists to read
/// those sentences back into fields. With the stage 9 corpus seeded and the engine still on
/// <c>e3-v1</c>, that extractor is the one witness that has seen a real signal of all six rules — the
/// stage 8 corpus fired three of them — so what it reads here is the standard the field-emitting
/// engine has to meet, for three hundred evaluations, without a single sentence invented in a test.
/// </para>
/// <para>
/// The file is committed before the engine is touched, so the order of the commits is itself part of
/// the argument: the prediction precedes the measurement and anybody can check that it did. It is the
/// same shape of falsification as the archetype table of <c>E9A</c>.
/// </para>
/// <para>
/// <strong>The capture is never regenerated by this test.</strong> A golden that rewrites itself
/// asserts nothing at all: it would turn a change of behaviour into a change of file and stay green
/// through both. When it disagrees it writes what it saw to a temporary file and names it, so the
/// difference can be read; replacing the capture is a deliberate edit with its own commit and its own
/// stated reason.
/// </para>
/// </remarks>
public sealed class SignalFactsGoldenTests : IClassFixture<SalvoApiFactory>
{
    private static readonly JsonSerializerOptions GoldenFormat = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        WriteIndented = true,
    };

    private readonly SalvoApiFactory factory;

    public SignalFactsGoldenTests(SalvoApiFactory factory)
    {
        this.factory = factory;
    }

    [Fact]
    public async Task EveryTypedFieldOfTheCorpusMatchesTheGoldenCapture()
    {
        var actual = await CaptureAsync();
        var expected = ReadGolden(actual);

        Assert.Equal(expected.Length, actual.Count);

        // Six rules, because that is the whole reason the fixture came first. A capture that
        // covered five would certify five.
        Assert.Equal(
            RiskRuleNames.CanonicalOrder.Order(StringComparer.Ordinal),
            actual
                .SelectMany(entry => entry.Signals)
                .Select(signal => signal.Rule)
                .Distinct()
                .Order(StringComparer.Ordinal));

        foreach (var (expectedEntry, actualEntry) in expected.Zip(actual))
        {
            Assert.Equal(expectedEntry.Reference, actualEntry.Reference);
            Assert.Equal(expectedEntry.Score, actualEntry.Score);
            Assert.Equal(
                expectedEntry.Signals.Select(signal => signal.Rule),
                actualEntry.Signals.Select(signal => signal.Rule));

            foreach (var (expectedSignal, actualSignal) in expectedEntry.Signals.Zip(actualEntry.Signals))
            {
                // The engine writes no prose any more, and the capture keeps the sentence each set
                // of fields was read from. Everything else is compared.
                Assert.NotNull(expectedSignal.Detail);
                Assert.Null(actualSignal.Detail);

                // Record equality, so every field of the table is compared and a field added later
                // cannot slip through unchecked. Decimals compare by value: 4.0 and 4 are the same
                // number, and the scale of the canonical string is asserted where the string is
                // built, not here.
                Assert.Equal(expectedSignal with { Detail = null }, actualSignal);
            }
        }
    }

    /// <summary>
    /// The grounding facts of every evaluation, built from fields, against the same facts built
    /// from the sentences those fields were read out of.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The other half of the oracle. The first test says the fields agree; this one says the
    /// <em>consequences</em> of the fields agree, over the one thing the fields are for — deciding
    /// whether a figure in a summary was measured or invented. A field carried across correctly but
    /// dropped from the enumeration would pass the first test and fail here.
    /// </para>
    /// <para>
    /// <strong>The two sets are not equal, and the difference is the point.</strong> Every fact the
    /// prose produced is still a fact, which is the regression this guards. What the fields add is
    /// the median in units: the engine wrote cents and nobody writing a sentence about money does,
    /// so «la mediana fue 86,85 BRL» used to be a true figure the verifier refused. The test
    /// computes that addition independently and asserts the difference is exactly it — anything
    /// else appearing or disappearing fails.
    /// </para>
    /// </remarks>
    [Fact]
    public async Task TheFactsBuiltFromFieldsLoseNothingTheProseGrounded()
    {
        using var client = await factory.CreateMigratedClientAsync();
        (await client.PostAsync("/api/demo-data/seed", null)).EnsureSuccessStatusCode();

        await using var scope = factory.Services.CreateAsyncScope();
        var dbContext = scope.ServiceProvider.GetRequiredService<SalvoDbContext>();
        var orders = await dbContext.Orders.AsNoTracking().ToDictionaryAsync(order => order.Id);
        var handler = scope.ServiceProvider.GetRequiredService<EvaluateLocalRiskHandler>();
        var evaluation = await handler.HandleAsync(CancellationToken.None);
        var config = RuleConfig.ForVersion(evaluation.ConfigVersion);
        var prose = ReadGolden([]).ToDictionary(entry => entry.Reference);
        var grounded = ReadGroundingGolden(prose.Values);

        var compared = 0;
        foreach (var assessment in evaluation.Assessments.Where(one => one.Signals.Count > 0))
        {
            var order = orders[assessment.OrderId];
            var input = new ExplanationInput(
                assessment.Score,
                "MEDIUM",
                evaluation.ConfigVersion,
                "e4-v1",
                assessment.Signals,
                order.AmountCents,
                order.CurrencyCode,
                order.CountryCode,
                order.Channel,
                order.OccurredAt);

            var captured = prose[order.MerchantReferenceId];
            var fromProse = grounded[order.MerchantReferenceId];
            var fromFields = SignalFacts.ForAll(assessment.Signals)
                .SelectMany(signal => signal.Numbers)
                .SelectMany(token => token.Readings)
                .Select(reading => reading.Value)
                .Distinct()
                .Order()
                .ToArray();

            // The rest of `ExplanationFacts` — the score, the threshold, the cap, the instant — is
            // untouched by `e3-v2`, so what is compared is the part that changed: the numbers the
            // signals themselves contribute.
            Assert.NotEmpty(ExplanationFacts.For(input, SignalFacts.ForAll(assessment.Signals), config).Values);

            var added = fromFields.Except(fromProse).ToHashSet();
            // The one deliberate addition: an amount in the units anybody writes it in. The engine
            // stated cents and a sentence about money never does, so «la mediana fue 149,37 BRL» was
            // a true figure the verifier refused. Computed here from the capture rather than taken
            // from the code under test.
            var amountsInUnits = captured.Signals
                .SelectMany(signal => new[] { signal.AmountCents, signal.MedianCents })
                .Where(cents => cents is not null)
                .SelectMany(cents => Enumerable
                    .Range(0, NumberTokenizer.MaximumRoundedDecimals + 1)
                    .Select(decimals => Math.Round(
                        cents!.Value / 100m,
                        decimals,
                        MidpointRounding.AwayFromZero)))
                .ToHashSet();

            Assert.Empty(fromProse.Except(fromFields));
            Assert.Empty(added.Except(amountsInUnits));
            compared++;
        }

        Assert.Equal(prose.Count, compared);
    }

    /// <summary>
    /// Runs the engine over the seeded corpus and reads every signal into fields.
    /// </summary>
    private async Task<IReadOnlyList<GoldenEntry>> CaptureAsync()
    {
        using var client = await factory.CreateMigratedClientAsync();
        var seed = await client.PostAsync("/api/demo-data/seed", null);
        seed.EnsureSuccessStatusCode();

        await using var scope = factory.Services.CreateAsyncScope();
        var dbContext = scope.ServiceProvider.GetRequiredService<SalvoDbContext>();
        var references = await dbContext.Orders
            .AsNoTracking()
            .ToDictionaryAsync(order => order.Id, order => order.MerchantReferenceId);
        var handler = scope.ServiceProvider.GetRequiredService<EvaluateLocalRiskHandler>();
        var evaluation = await handler.HandleAsync(CancellationToken.None);

        // The capture in the file was taken under `e3-v1`, from prose. This runs under `e3-v2`,
        // from fields. That the two agree is the whole point, and it stops meaning anything the day
        // this line stops saying which version produced the numbers being compared.
        Assert.Equal("e3-v2", evaluation.ConfigVersion);

        return evaluation.Assessments
            .Where(assessment => assessment.Signals.Count > 0)
            .Select(assessment => new GoldenEntry(
                references[assessment.OrderId],
                assessment.Score,
                [.. assessment.Signals.Select(Project)]))
            .OrderBy(entry => entry.Reference, StringComparer.Ordinal)
            .ToArray();
    }

    /// <summary>
    /// One signal, as the fields it means.
    /// </summary>
    /// <remarks>
    /// It reads the fields the engine hands over. Until <c>e3-v2</c> it went through the extractor,
    /// which is what the capture recorded; the file has not moved since, so this is the comparison
    /// the whole task turns on.
    /// </remarks>
    private static GoldenSignal Project(RiskSignal signal)
    {
        var facts = SignalFacts.For(signal);

        return new(
            facts.Rule,
            facts.Weight,
            // The prose is what the fields were read out of, and the engine writes none any more.
            // The capture keeps it as the record of where the numbers came from.
            signal.Detail,
            facts.AmountCents,
            facts.CurrencyCode,
            facts.Ratio,
            facts.Scope switch
            {
                AmountMedianScope.Buyer => "buyer",
                AmountMedianScope.Merchant => "merchant",
                _ => null,
            },
            facts.MedianCents,
            facts.HistoryCount,
            facts.WindowDays,
            facts.OrderCount,
            facts.WindowMinutes,
            facts.Threshold,
            facts.FromCountry,
            facts.ToCountry,
            facts.ElapsedMinutes,
            facts.BucketStartHour,
            facts.BucketEndHour,
            facts.TimeZoneId,
            facts.ObservedCount,
            facts.TotalCount,
            facts.SharePercent,
            facts.Country,
            facts.HabitualCountry);
    }

    /// <summary>
    /// Reads the capture from the source tree, never from a build output, so that deleting the file
    /// fails the test instead of finding a stale copy beside the assembly.
    /// </summary>
    private static GoldenEntry[] ReadGolden(IReadOnlyList<GoldenEntry> actual)
    {
        var path = GoldenPath();
        if (!File.Exists(path))
        {
            Assert.Fail(
                $"The golden capture is missing: {path}. It is never written by this test. What "
                + $"the engine produces now was left at {WriteActual(actual)} so it can be read, "
                + "and putting it in place is a deliberate edit with its own commit.");
        }

        var parsed = JsonSerializer.Deserialize<GoldenEntry[]>(File.ReadAllText(path), GoldenFormat);

        return parsed ?? throw new InvalidOperationException($"The golden capture at {path} is not a JSON array.");
    }

    /// <summary>
    /// What the frozen grounding capture says is what reading the frozen prose produces.
    /// </summary>
    /// <remarks>
    /// The certification of the file the previous test leans on, and the last thing the extractor is
    /// asked to do. It is deleted in the next commit and this test goes with it; the file it signed
    /// stays, and the comparison it makes possible keeps running for good.
    /// </remarks>
    [Fact]
    public void TheGroundingCaptureIsWhatTheExtractorReadsFromTheFrozenProse()
    {
        var prose = ReadGolden([]);
        var frozen = ReadGroundingGolden(prose);

        foreach (var entry in prose)
        {
            var signals = SignalFacts.ForAll(
                [.. entry.Signals.Select(signal =>
                    new RiskSignal(signal.Rule, signal.Weight) { Detail = signal.Detail })]);

            Assert.Equal(
                frozen[entry.Reference],
                signals
                    .SelectMany(signal => signal.Numbers)
                    .SelectMany(token => token.Readings)
                    .Select(reading => reading.Value)
                    .Distinct()
                    .Order()
                    .ToArray());
        }
    }

    /// <summary>
    /// The grounding facts the extractor derived from the frozen `e3-v1` prose, read from a file.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Frozen for the same reason the fields are: the extractor is deleted in the commit after this
    /// one, and an assertion that dies with the thing it was checking leaves nothing behind. The
    /// prose it was derived from is itself frozen in <c>signal-facts.v2.json</c>, so this file is a
    /// pure function of a file that predates the engine change — which is what keeps it evidence and
    /// not a snapshot of whatever the code happens to do now.
    /// </para>
    /// <para>
    /// While the extractor is still here, the values are certified against it on every run: what the
    /// file says has to be what reading that prose produces. That check goes when the extractor
    /// goes, and the file it certified stays.
    /// </para>
    /// </remarks>
    private static Dictionary<string, decimal[]> ReadGroundingGolden(IReadOnlyCollection<GoldenEntry> prose)
    {
        var path = Path.Combine(Path.GetDirectoryName(GoldenSourceDirectory())!, "Goldens", "grounding-facts.v2.json");
        if (!File.Exists(path))
        {
            var observed = prose.ToDictionary(
                entry => entry.Reference,
                entry => SignalFacts
                    .ForAll([.. entry.Signals.Select(signal =>
                        new RiskSignal(signal.Rule, signal.Weight) { Detail = signal.Detail })])
                    .SelectMany(signal => signal.Numbers)
                    .SelectMany(token => token.Readings)
                    .Select(reading => reading.Value)
                    .Distinct()
                    .Order()
                    .ToArray());
            var temporary = Path.Combine(Path.GetTempPath(), "salvo-grounding-facts.actual.json");
            File.WriteAllText(temporary, JsonSerializer.Serialize(observed, GoldenFormat));
            Assert.Fail(
                $"The grounding capture is missing: {path}. It is never written by this test; what "
                + $"the extractor reads from the frozen prose was left at {temporary}.");
        }

        var parsed = JsonSerializer.Deserialize<Dictionary<string, decimal[]>>(
            File.ReadAllText(path),
            GoldenFormat) ?? throw new InvalidOperationException($"The capture at {path} is not an object.");

        Assert.Equal(prose.Count, parsed.Count);

        return parsed;
    }

    private static string WriteActual(IReadOnlyList<GoldenEntry> actual)
    {
        var path = Path.Combine(Path.GetTempPath(), "salvo-signal-facts.actual.json");
        File.WriteAllText(path, JsonSerializer.Serialize(actual, GoldenFormat));

        return path;
    }

    private static string GoldenPath([CallerFilePath] string thisFile = "")
    {
        return Path.Combine(Path.GetDirectoryName(thisFile)!, "Goldens", "signal-facts.v2.json");
    }

    private static string GoldenSourceDirectory([CallerFilePath] string thisFile = "") => thisFile;

    /// <summary>One evaluation that raised at least one signal.</summary>
    internal sealed record GoldenEntry(
        string Reference,
        int Score,
        IReadOnlyList<GoldenSignal> Signals);

    /// <summary>
    /// One signal: its rule, its weight, the <c>e3-v1</c> prose exactly as the engine wrote it, and
    /// every typed field of the <c>E9B</c> table, in the order that table declares them.
    /// </summary>
    internal sealed record GoldenSignal(
        string Rule,
        int Weight,
        string? Detail,
        long? AmountCents,
        string? CurrencyCode,
        decimal? Ratio,
        string? Scope,
        long? MedianCents,
        int? HistoryCount,
        int? WindowDays,
        int? OrderCount,
        int? WindowMinutes,
        int? Threshold,
        string? FromCountry,
        string? ToCountry,
        decimal? ElapsedMinutes,
        int? BucketStartHour,
        int? BucketEndHour,
        string? TimeZoneId,
        int? ObservedCount,
        int? TotalCount,
        decimal? SharePercent,
        string? Country,
        string? HabitualCountry);
}
