using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Salvo.Application.Risk;
using Salvo.Domain.Explanations;
using Salvo.Domain.Risk;
using Salvo.Infrastructure.Persistence;

namespace Salvo.Api.IntegrationTests;

/// <summary>
/// The typed fields of every signal the demo corpus raises, pinned to a file.
/// </summary>
/// <remarks>
/// <para>
/// <strong>This is the oracle of <c>E9B</c>, and it only works because it was captured first.</strong>
/// The engine writes each signal as an English sentence, and <see cref="SignalFacts"/> exists to read
/// those sentences back into fields. With the stage 9 corpus seeded and the engine still on
/// <c>e3-v1</c>, that extractor is the one witness that has seen a real signal of all six rules — the
/// stage 8 corpus fired three of them — so what it reads here is the standard the field-emitting
/// engine has to meet, for three hundred evaluations, without a single sentence invented in a test.
/// </para>
/// <para>
/// The file is committed before the engine is touched, so the order of the commits is itself part of
/// the argument: the prediction precedes the measurement and anybody can check that it did. It is the
/// same shape of falsification as the archetype table of <c>E9A</c>.
/// </para>
/// <para>
/// <strong>The capture is never regenerated by this test.</strong> A golden that rewrites itself
/// asserts nothing at all: it would turn a change of behaviour into a change of file and stay green
/// through both. When it disagrees it writes what it saw to a temporary file and names it, so the
/// difference can be read; replacing the capture is a deliberate edit with its own commit and its own
/// stated reason.
/// </para>
/// </remarks>
public sealed class SignalFactsGoldenTests : IClassFixture<SalvoApiFactory>
{
    private static readonly JsonSerializerOptions GoldenFormat = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        WriteIndented = true,
    };

    private readonly SalvoApiFactory factory;

    public SignalFactsGoldenTests(SalvoApiFactory factory)
    {
        this.factory = factory;
    }

    [Fact]
    public async Task EveryTypedFieldOfTheCorpusMatchesTheGoldenCapture()
    {
        var actual = await CaptureAsync();
        var expected = ReadGolden(actual);

        Assert.Equal(expected.Length, actual.Count);

        // Six rules, because that is the whole reason the fixture came first. A capture that
        // covered five would certify five.
        Assert.Equal(
            RiskRuleNames.CanonicalOrder.Order(StringComparer.Ordinal),
            actual
                .SelectMany(entry => entry.Signals)
                .Select(signal => signal.Rule)
                .Distinct()
                .Order(StringComparer.Ordinal));

        foreach (var (expectedEntry, actualEntry) in expected.Zip(actual))
        {
            Assert.Equal(expectedEntry.Reference, actualEntry.Reference);
            Assert.Equal(expectedEntry.Score, actualEntry.Score);
            Assert.Equal(
                expectedEntry.Signals.Select(signal => signal.Rule),
                actualEntry.Signals.Select(signal => signal.Rule));

            foreach (var (expectedSignal, actualSignal) in expectedEntry.Signals.Zip(actualEntry.Signals))
            {
                // Record equality, so every field of the table is compared and a field added later
                // cannot slip through unchecked. Decimals compare by value: 4.0 and 4 are the same
                // number, and the scale of the canonical string is asserted where the string is
                // built, not here.
                Assert.Equal(expectedSignal, actualSignal);
            }
        }
    }

    /// <summary>
    /// Runs the engine over the seeded corpus and reads every signal into fields.
    /// </summary>
    private async Task<IReadOnlyList<GoldenEntry>> CaptureAsync()
    {
        using var client = await factory.CreateMigratedClientAsync();
        var seed = await client.PostAsync("/api/demo-data/seed", null);
        seed.EnsureSuccessStatusCode();

        await using var scope = factory.Services.CreateAsyncScope();
        var dbContext = scope.ServiceProvider.GetRequiredService<SalvoDbContext>();
        var references = await dbContext.Orders
            .AsNoTracking()
            .ToDictionaryAsync(order => order.Id, order => order.MerchantReferenceId);
        var handler = scope.ServiceProvider.GetRequiredService<EvaluateLocalRiskHandler>();
        var evaluation = await handler.HandleAsync(CancellationToken.None);

        Assert.Equal("e3-v1", evaluation.ConfigVersion);

        return evaluation.Assessments
            .Where(assessment => assessment.Signals.Count > 0)
            .Select(assessment => new GoldenEntry(
                references[assessment.OrderId],
                assessment.Score,
                [.. assessment.Signals.Select(Project)]))
            .OrderBy(entry => entry.Reference, StringComparer.Ordinal)
            .ToArray();
    }

    /// <summary>
    /// One signal, as the fields it means.
    /// </summary>
    /// <remarks>
    /// While the engine writes prose this goes through the extractor, which is the point of the
    /// capture. When the engine emits the fields itself, this reads them directly and the file it is
    /// compared against does not move.
    /// </remarks>
    private static GoldenSignal Project(RiskSignal signal)
    {
        var facts = SignalFacts.Parse(signal);

        return new(
            facts.Rule,
            facts.Weight,
            signal.Detail,
            facts.AmountCents,
            facts.CurrencyCode,
            facts.Ratio,
            facts.Scope switch
            {
                AmountMedianScope.Buyer => "buyer",
                AmountMedianScope.Merchant => "merchant",
                _ => null,
            },
            facts.MedianCents,
            facts.HistoryCount,
            facts.WindowDays,
            facts.OrderCount,
            facts.WindowMinutes,
            facts.Threshold,
            facts.FromCountry,
            facts.ToCountry,
            facts.ElapsedMinutes,
            facts.BucketStartHour,
            facts.BucketEndHour,
            facts.TimeZoneId,
            facts.ObservedCount,
            facts.TotalCount,
            facts.SharePercent,
            facts.Country,
            facts.HabitualCountry);
    }

    /// <summary>
    /// Reads the capture from the source tree, never from a build output, so that deleting the file
    /// fails the test instead of finding a stale copy beside the assembly.
    /// </summary>
    private static GoldenEntry[] ReadGolden(IReadOnlyList<GoldenEntry> actual)
    {
        var path = GoldenPath();
        if (!File.Exists(path))
        {
            Assert.Fail(
                $"The golden capture is missing: {path}. It is never written by this test. What "
                + $"the engine produces now was left at {WriteActual(actual)} so it can be read, "
                + "and putting it in place is a deliberate edit with its own commit.");
        }

        var parsed = JsonSerializer.Deserialize<GoldenEntry[]>(File.ReadAllText(path), GoldenFormat);

        return parsed ?? throw new InvalidOperationException($"The golden capture at {path} is not a JSON array.");
    }

    private static string WriteActual(IReadOnlyList<GoldenEntry> actual)
    {
        var path = Path.Combine(Path.GetTempPath(), "salvo-signal-facts.actual.json");
        File.WriteAllText(path, JsonSerializer.Serialize(actual, GoldenFormat));

        return path;
    }

    private static string GoldenPath([CallerFilePath] string thisFile = "")
    {
        return Path.Combine(Path.GetDirectoryName(thisFile)!, "Goldens", "signal-facts.v2.json");
    }

    /// <summary>One evaluation that raised at least one signal.</summary>
    internal sealed record GoldenEntry(
        string Reference,
        int Score,
        IReadOnlyList<GoldenSignal> Signals);

    /// <summary>
    /// One signal: its rule, its weight, the <c>e3-v1</c> prose exactly as the engine wrote it, and
    /// every typed field of the <c>E9B</c> table, in the order that table declares them.
    /// </summary>
    internal sealed record GoldenSignal(
        string Rule,
        int Weight,
        string? Detail,
        long? AmountCents,
        string? CurrencyCode,
        decimal? Ratio,
        string? Scope,
        long? MedianCents,
        int? HistoryCount,
        int? WindowDays,
        int? OrderCount,
        int? WindowMinutes,
        int? Threshold,
        string? FromCountry,
        string? ToCountry,
        decimal? ElapsedMinutes,
        int? BucketStartHour,
        int? BucketEndHour,
        string? TimeZoneId,
        int? ObservedCount,
        int? TotalCount,
        decimal? SharePercent,
        string? Country,
        string? HabitualCountry);
}
