// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Salvo.Infrastructure.Persistence;

#nullable disable

namespace Salvo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SalvoDbContext))]
    [Migration("20260902190108_RiskEvaluationPersistence")]
    partial class RiskEvaluationPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Salvo.Domain.Evaluation.OrderEvaluationLabel", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsFraudLabel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_fraud_label");

                    b.HasKey("OrderId");

                    b.ToTable("order_evaluation_labels", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_evaluation_labels_created_at_utc", "length(created_at_utc) = 24 AND substr(created_at_utc, 24, 1) = 'Z'");

                            t.HasCheckConstraint("ck_order_evaluation_labels_is_fraud_label", "is_fraud_label IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Salvo.Domain.Orders.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount_cents");

                    b.Property<string>("BuyerReferenceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("buyer_reference_id");

                    b.Property<string>("Channel")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("channel");

                    b.Property<string>("City")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("country_code");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_code");

                    b.Property<string>("DeviceSessionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("device_session_id");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("merchant_id");

                    b.Property<string>("MerchantReferenceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("merchant_reference_id");

                    b.Property<string>("OccurredAt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId", "MerchantReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_merchant_reference");

                    b.HasIndex("OccurredAt", "MerchantId", "MerchantReferenceId")
                        .HasDatabaseName("ix_orders_chronological");

                    b.HasIndex("MerchantId", "BuyerReferenceId", "CurrencyCode", "OccurredAt", "MerchantReferenceId")
                        .HasDatabaseName("ix_orders_buyer_currency_history");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_orders_amount_cents", "amount_cents >= 1 AND amount_cents <= 1000000000000");

                            t.HasCheckConstraint("ck_orders_buyer_reference_id", "length(buyer_reference_id) BETWEEN 5 AND 64 AND buyer_reference_id GLOB 'BUY_*' AND buyer_reference_id NOT GLOB '*[^A-Z0-9_-]*'");

                            t.HasCheckConstraint("ck_orders_channel", "channel IS NULL OR channel IN ('WEB', 'MOBILE_APP', 'MARKETPLACE')");

                            t.HasCheckConstraint("ck_orders_city", "city IS NULL OR length(city) <= 80");

                            t.HasCheckConstraint("ck_orders_country_code", "length(country_code) = 2 AND country_code NOT GLOB '*[^A-Z]*'");

                            t.HasCheckConstraint("ck_orders_created_at_utc", "length(created_at_utc) = 24 AND substr(created_at_utc, 24, 1) = 'Z'");

                            t.HasCheckConstraint("ck_orders_currency_code", "currency_code IN ('UYU', 'BRL', 'USD')");

                            t.HasCheckConstraint("ck_orders_device_session_id", "device_session_id IS NULL OR (length(device_session_id) BETWEEN 5 AND 64 AND device_session_id GLOB 'DEV_*' AND device_session_id NOT GLOB '*[^A-Z0-9_-]*')");

                            t.HasCheckConstraint("ck_orders_merchant_id", "length(merchant_id) BETWEEN 5 AND 64 AND merchant_id GLOB 'MER_*' AND merchant_id NOT GLOB '*[^A-Z0-9_-]*'");

                            t.HasCheckConstraint("ck_orders_merchant_reference_id", "length(merchant_reference_id) BETWEEN 5 AND 64 AND merchant_reference_id GLOB 'ORD_*' AND merchant_reference_id NOT GLOB '*[^A-Z0-9_-]*'");

                            t.HasCheckConstraint("ck_orders_occurred_at_utc", "length(occurred_at_utc) = 24 AND substr(occurred_at_utc, 24, 1) = 'Z'");
                        });
                });

            modelBuilder.Entity("Salvo.Domain.Risk.RiskEvaluation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<string>("EvaluationFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluation_fingerprint");

                    b.Property<string>("ExternalEvaluationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("external_evaluation_id");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<string>("RuleConfigVersion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("rule_config_version");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.Property<string>("SignalsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("signals_json");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationFingerprint")
                        .IsUnique()
                        .HasDatabaseName("ux_risk_evaluations_local_fingerprint")
                        .HasFilter("source = 'LOCAL'");

                    b.HasIndex("OrderId", "CreatedAt")
                        .HasDatabaseName("ix_risk_evaluations_order");

                    b.ToTable("risk_evaluations", null, t =>
                        {
                            t.HasCheckConstraint("ck_risk_evaluations_created_at_utc", "length(created_at_utc) = 24 AND substr(created_at_utc, 24, 1) = 'Z'");

                            t.HasCheckConstraint("ck_risk_evaluations_fingerprint", "evaluation_fingerprint IS NULL OR (length(evaluation_fingerprint) = 64 AND evaluation_fingerprint NOT GLOB '*[^0-9a-f]*')");

                            t.HasCheckConstraint("ck_risk_evaluations_local_completeness", "source <> 'LOCAL' OR (rule_config_version IS NOT NULL AND score IS NOT NULL AND signals_json IS NOT NULL AND evaluation_fingerprint IS NOT NULL)");

                            t.HasCheckConstraint("ck_risk_evaluations_score", "score IS NULL OR (score >= 0 AND score <= 100)");

                            t.HasCheckConstraint("ck_risk_evaluations_source", "source IN ('LOCAL', 'EXTERNAL_MOCK', 'KOIN_SANDBOX')");

                            t.HasCheckConstraint("ck_risk_evaluations_status", "status IN ('PENDING', 'APPROVED', 'DENIED', 'ERROR')");
                        });
                });

            modelBuilder.Entity("Salvo.Domain.Risk.RunEvaluation", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<string>("OrderId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<string>("EvaluationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluation_id");

                    b.HasKey("RunId", "OrderId")
                        .HasName("pk_run_evaluations");

                    b.HasIndex("EvaluationId")
                        .HasDatabaseName("ix_run_evaluations_evaluation");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_run_evaluations_order");

                    b.ToTable("run_evaluations", (string)null);
                });

            modelBuilder.Entity("Salvo.Domain.Risk.ScoringRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CompletedAt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<int>("EvaluationsCreated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("evaluations_created");

                    b.Property<int>("EvaluationsReused")
                        .HasColumnType("INTEGER")
                        .HasColumnName("evaluations_reused");

                    b.Property<int>("OrderCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_count");

                    b.Property<string>("RuleConfigVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("rule_config_version");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_sequence");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_scoring_runs_run_sequence");

                    b.ToTable("scoring_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_scoring_runs_completed_at_utc", "length(completed_at_utc) = 24 AND substr(completed_at_utc, 24, 1) = 'Z' AND completed_at_utc >= started_at_utc");

                            t.HasCheckConstraint("ck_scoring_runs_counts", "order_count >= 0 AND evaluations_created >= 0 AND evaluations_reused >= 0 AND evaluations_created + evaluations_reused = order_count");

                            t.HasCheckConstraint("ck_scoring_runs_run_sequence", "run_sequence >= 1");

                            t.HasCheckConstraint("ck_scoring_runs_started_at_utc", "length(started_at_utc) = 24 AND substr(started_at_utc, 24, 1) = 'Z'");
                        });
                });

            modelBuilder.Entity("Salvo.Domain.Evaluation.OrderEvaluationLabel", b =>
                {
                    b.HasOne("Salvo.Domain.Orders.Order", null)
                        .WithOne()
                        .HasForeignKey("Salvo.Domain.Evaluation.OrderEvaluationLabel", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Salvo.Domain.Risk.RiskEvaluation", b =>
                {
                    b.HasOne("Salvo.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Salvo.Domain.Risk.RunEvaluation", b =>
                {
                    b.HasOne("Salvo.Domain.Risk.RiskEvaluation", null)
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Salvo.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Salvo.Domain.Risk.ScoringRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
