// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Salvo.Infrastructure.Persistence;

#nullable disable

namespace Salvo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SalvoDbContext))]
    [Migration("20260905013514_Explanations")]
    partial class Explanations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Salvo.Domain.Alerts.Alert", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AlertPolicyVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("alert_policy_version");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<string>("ReviewedAt")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<string>("RiskEvaluationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("risk_evaluation_id");

                    b.Property<int>("RiskScoreSnapshot")
                        .HasColumnType("INTEGER")
                        .HasColumnName("risk_score_snapshot");

                    b.Property<string>("SignalsSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("signals_snapshot_json");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("SupersedesAlertId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("supersedes_alert_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_alerts_open_order")
                        .HasFilter("status = 'OPEN'");

                    b.HasIndex("RiskEvaluationId")
                        .IsUnique()
                        .HasDatabaseName("ux_alerts_risk_evaluation");

                    b.HasIndex("SupersedesAlertId");

                    b.HasIndex("OrderId", "CreatedAt")
                        .HasDatabaseName("ix_alerts_order_created");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_alerts_status_created");

                    b.ToTable("alerts", null, t =>
                        {
                            t.HasCheckConstraint("ck_alerts_created_at_utc", "length(created_at_utc) = 24 AND substr(created_at_utc, 24, 1) = 'Z'");

                            t.HasCheckConstraint("ck_alerts_review_consistency", "(status = 'OPEN' AND reviewed_at_utc IS NULL) OR (status <> 'OPEN' AND reviewed_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_alerts_reviewed_at_utc", "reviewed_at_utc IS NULL OR (length(reviewed_at_utc) = 24 AND substr(reviewed_at_utc, 24, 1) = 'Z' AND reviewed_at_utc >= created_at_utc)");

                            t.HasCheckConstraint("ck_alerts_risk_score_snapshot", "risk_score_snapshot >= 0 AND risk_score_snapshot <= 100");

                            t.HasCheckConstraint("ck_alerts_status", "status IN ('OPEN', 'CONFIRMED_SAFE', 'REPORTED_FRAUD')");

                            t.HasCheckConstraint("ck_alerts_supersedes_other", "supersedes_alert_id IS NULL OR supersedes_alert_id <> id");
                        });
                });

            modelBuilder.Entity("Salvo.Domain.Alerts.AlertReview", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AlertId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("alert_id");

                    b.Property<string>("ExplanationId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("explanation_id");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("new_status");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_status");

                    b.Property<string>("ReviewedAt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewed_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AlertId")
                        .IsUnique()
                        .HasDatabaseName("ux_alert_reviews_alert");

                    b.HasIndex("ExplanationId");

                    b.ToTable("alert_reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_alert_reviews_new_status", "new_status IN ('CONFIRMED_SAFE', 'REPORTED_FRAUD')");

                            t.HasCheckConstraint("ck_alert_reviews_previous_status", "previous_status IN ('OPEN', 'CONFIRMED_SAFE', 'REPORTED_FRAUD')");

                            t.HasCheckConstraint("ck_alert_reviews_reviewed_at_utc", "length(reviewed_at_utc) = 24 AND substr(reviewed_at_utc, 24, 1) = 'Z'");

                            t.HasCheckConstraint("ck_alert_reviews_transition", "new_status <> previous_status");
                        });
                });

            modelBuilder.Entity("Salvo.Domain.Evaluation.OrderEvaluationLabel", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsFraudLabel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_fraud_label");

                    b.HasKey("OrderId");

                    b.ToTable("order_evaluation_labels", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_evaluation_labels_created_at_utc", "length(created_at_utc) = 24 AND substr(created_at_utc, 24, 1) = 'Z'");

                            t.HasCheckConstraint("ck_order_evaluation_labels_is_fraud_label", "is_fraud_label IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Salvo.Domain.Explanations.AlertExplanation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AlertPolicyVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("alert_policy_version");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_count");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(21)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureDetail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_detail");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("input_tokens");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("INTEGER")
                        .HasColumnName("output_tokens");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_version");

                    b.Property<string>("ReferencedRulesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("referenced_rules_json");

                    b.Property<string>("RequestedAt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_at_utc");

                    b.Property<string>("RequestedFromAlertId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_from_alert_id");

                    b.Property<string>("RiskEvaluationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("risk_evaluation_id");

                    b.Property<long>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER")
                        .HasColumnName("row_version");

                    b.Property<string>("SettledAt")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("settled_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("TemplateVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("template_version");

                    b.HasKey("Id");

                    b.HasIndex("RequestedFromAlertId")
                        .HasDatabaseName("ix_alert_explanations_requested_from_alert");

                    b.HasIndex("RiskEvaluationId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ux_alert_explanations_pending_evaluation")
                        .HasFilter("status = 'PENDING'");

                    b.HasIndex("RiskEvaluationId", "Provider", "TemplateVersion", "AlertPolicyVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_alert_explanations_identity");

                    b.ToTable("alert_explanations", null, t =>
                        {
                            t.HasCheckConstraint("ck_alert_explanations_attempts", "attempt_count BETWEEN 0 AND 3");

                            t.HasCheckConstraint("ck_alert_explanations_failure", "failure_code IS NULL OR status = 'FAILED'");

                            t.HasCheckConstraint("ck_alert_explanations_failure_code", "failure_code IS NULL OR failure_code IN ('PROVIDER_UNAVAILABLE', 'PROVIDER_TIMEOUT', 'PROVIDER_REFUSED', 'MALFORMED_OUTPUT', 'NOT_GROUNDED_NUMBER', 'NOT_GROUNDED_RULE', 'TOO_LONG', 'CANCELLED', 'ATTEMPT_LIMIT_REACHED')");

                            t.HasCheckConstraint("ck_alert_explanations_provider", "provider IN ('MOCK', 'ANTHROPIC')");

                            t.HasCheckConstraint("ck_alert_explanations_ready", "(status = 'READY' AND summary IS NOT NULL AND referenced_rules_json IS NOT NULL) OR (status <> 'READY' AND summary IS NULL AND referenced_rules_json IS NULL)");

                            t.HasCheckConstraint("ck_alert_explanations_requested_at_utc", "length(requested_at_utc) = 24 AND substr(requested_at_utc, 24, 1) = 'Z'");

                            t.HasCheckConstraint("ck_alert_explanations_settled", "(status = 'PENDING' AND settled_at_utc IS NULL) OR (status <> 'PENDING' AND settled_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_alert_explanations_settled_at_utc", "settled_at_utc IS NULL OR (length(settled_at_utc) = 24 AND substr(settled_at_utc, 24, 1) = 'Z' AND settled_at_utc >= requested_at_utc)");

                            t.HasCheckConstraint("ck_alert_explanations_status", "status IN ('PENDING', 'READY', 'FAILED')");

                            t.HasCheckConstraint("ck_alert_explanations_summary_length", "summary IS NULL OR length(summary) <= 1200");

                            t.HasCheckConstraint("ck_alert_explanations_tokens", "(input_tokens IS NULL OR input_tokens >= 0) AND (output_tokens IS NULL OR output_tokens >= 0)");
                        });
                });

            modelBuilder.Entity("Salvo.Domain.External.CallbackReceipt", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("deduplication_key");

                    b.Property<string>("ExternalEvaluationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("external_evaluation_id");

                    b.Property<string>("LastSeenAt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("ProcessedAt")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderInstant")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_instant_utc");

                    b.Property<string>("ReceivedAt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(129)
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_id");

                    b.Property<int>("ReplayCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("replay_count");

                    b.Property<int?>("ReportedScore")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reported_score");

                    b.Property<string>("ReportedStatus")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("reported_status");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "DeduplicationKey")
                        .IsUnique()
                        .HasDatabaseName("ux_callback_receipts_provider_key");

                    b.HasIndex("Provider", "ExternalEvaluationId")
                        .HasDatabaseName("ix_callback_receipts_provider_identifier");

                    b.HasIndex("Provider", "ReferenceId")
                        .HasDatabaseName("ix_callback_receipts_provider_reference");

                    b.HasIndex("Provider", "Status")
                        .HasDatabaseName("ix_callback_receipts_provider_status");

                    b.ToTable("callback_receipts", null, t =>
                        {
                            t.HasCheckConstraint("ck_callback_receipts_correlation", "external_evaluation_id IS NOT NULL OR reference_id IS NOT NULL");

                            t.HasCheckConstraint("ck_callback_receipts_last_seen_at_utc", "length(last_seen_at_utc) = 24 AND substr(last_seen_at_utc, 24, 1) = 'Z' AND last_seen_at_utc >= received_at_utc");

                            t.HasCheckConstraint("ck_callback_receipts_processed", "(status = 'UNMATCHED' AND processed_at_utc IS NULL) OR (status <> 'UNMATCHED' AND processed_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_callback_receipts_processed_at_utc", "processed_at_utc IS NULL OR (length(processed_at_utc) = 24 AND substr(processed_at_utc, 24, 1) = 'Z')");

                            t.HasCheckConstraint("ck_callback_receipts_provider", "provider IN ('EXTERNAL_MOCK', 'KOIN_SANDBOX')");

                            t.HasCheckConstraint("ck_callback_receipts_provider_instant_utc", "provider_instant_utc IS NULL OR (length(provider_instant_utc) = 24 AND substr(provider_instant_utc, 24, 1) = 'Z')");

                            t.HasCheckConstraint("ck_callback_receipts_received_at_utc", "length(received_at_utc) = 24 AND substr(received_at_utc, 24, 1) = 'Z'");

                            t.HasCheckConstraint("ck_callback_receipts_replay_count", "replay_count >= 0");

                            t.HasCheckConstraint("ck_callback_receipts_reported_score", "reported_score IS NULL OR reported_score >= 0");

                            t.HasCheckConstraint("ck_callback_receipts_reported_status", "reported_status IN ('PENDING', 'APPROVED', 'DENIED', 'ERROR')");

                            t.HasCheckConstraint("ck_callback_receipts_status", "status IN ('APPLIED', 'NO_OP', 'SUPERSEDED', 'CONFLICTING', 'UNMATCHED')");
                        });
                });

            modelBuilder.Entity("Salvo.Domain.External.ExternalEvaluation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_count");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT")
                        .HasColumnName("error_code");

                    b.Property<string>("ExternalEvaluationId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("external_evaluation_id");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error_code");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(129)
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_id");

                    b.Property<string>("RequestedAt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("requested_at_utc");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.Property<string>("SettledAt")
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("settled_at_utc");

                    b.Property<string>("SettledBy")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT")
                        .HasColumnName("settled_by");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ux_external_evaluations_pending_order")
                        .HasFilter("status = 'PENDING'");

                    b.HasIndex("OrderId", "RequestedAt")
                        .HasDatabaseName("ix_external_evaluations_order_requested");

                    b.HasIndex("Provider", "ExternalEvaluationId")
                        .IsUnique()
                        .HasDatabaseName("ux_external_evaluations_provider_identifier")
                        .HasFilter("external_evaluation_id IS NOT NULL");

                    b.HasIndex("Provider", "ReferenceId")
                        .HasDatabaseName("ix_external_evaluations_provider_reference");

                    b.HasIndex("Status", "RequestedAt")
                        .HasDatabaseName("ix_external_evaluations_status_requested");

                    b.ToTable("external_evaluations", null, t =>
                        {
                            t.HasCheckConstraint("ck_external_evaluations_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_external_evaluations_error_code", "error_code IS NULL OR error_code IN ('UNREACHABLE', 'PROVIDER_REJECTED', 'TIMEOUT', 'PROVIDER_ERROR', 'INVALID_RESPONSE')");

                            t.HasCheckConstraint("ck_external_evaluations_error_status", "error_code IS NULL OR status = 'ERROR'");

                            t.HasCheckConstraint("ck_external_evaluations_last_error_code", "last_error_code IS NULL OR last_error_code IN ('UNREACHABLE', 'PROVIDER_REJECTED', 'TIMEOUT', 'PROVIDER_ERROR', 'INVALID_RESPONSE')");

                            t.HasCheckConstraint("ck_external_evaluations_provider", "provider IN ('EXTERNAL_MOCK', 'KOIN_SANDBOX')");

                            t.HasCheckConstraint("ck_external_evaluations_requested_at_utc", "length(requested_at_utc) = 24 AND substr(requested_at_utc, 24, 1) = 'Z'");

                            t.HasCheckConstraint("ck_external_evaluations_score", "score IS NULL OR score >= 0");

                            t.HasCheckConstraint("ck_external_evaluations_settled_at_utc", "settled_at_utc IS NULL OR (length(settled_at_utc) = 24 AND substr(settled_at_utc, 24, 1) = 'Z' AND settled_at_utc >= requested_at_utc)");

                            t.HasCheckConstraint("ck_external_evaluations_settled_by", "settled_by IS NULL OR settled_by IN ('SYNC', 'CALLBACK', 'RECONCILIATION')");

                            t.HasCheckConstraint("ck_external_evaluations_settled_by_consistency", "(settled_by IS NULL AND settled_at_utc IS NULL) OR (settled_by IS NOT NULL AND settled_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_external_evaluations_settlement", "(status = 'PENDING' AND settled_at_utc IS NULL) OR (status <> 'PENDING' AND settled_at_utc IS NOT NULL)");

                            t.HasCheckConstraint("ck_external_evaluations_status", "status IN ('PENDING', 'APPROVED', 'DENIED', 'ERROR')");

                            t.HasCheckConstraint("ck_external_evaluations_updated_at_utc", "length(updated_at_utc) = 24 AND substr(updated_at_utc, 24, 1) = 'Z' AND updated_at_utc >= requested_at_utc");
                        });
                });

            modelBuilder.Entity("Salvo.Domain.Orders.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount_cents");

                    b.Property<string>("BuyerReferenceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("buyer_reference_id");

                    b.Property<string>("Channel")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("channel");

                    b.Property<string>("City")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("country_code");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_code");

                    b.Property<string>("DeviceSessionId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("device_session_id");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("merchant_id");

                    b.Property<string>("MerchantReferenceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("merchant_reference_id");

                    b.Property<string>("OccurredAt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId", "MerchantReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_merchant_reference");

                    b.HasIndex("OccurredAt", "MerchantId", "MerchantReferenceId")
                        .HasDatabaseName("ix_orders_chronological");

                    b.HasIndex("MerchantId", "BuyerReferenceId", "CurrencyCode", "OccurredAt", "MerchantReferenceId")
                        .HasDatabaseName("ix_orders_buyer_currency_history");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_orders_amount_cents", "amount_cents >= 1 AND amount_cents <= 1000000000000");

                            t.HasCheckConstraint("ck_orders_buyer_reference_id", "length(buyer_reference_id) BETWEEN 5 AND 64 AND buyer_reference_id GLOB 'BUY_*' AND buyer_reference_id NOT GLOB '*[^A-Z0-9_-]*'");

                            t.HasCheckConstraint("ck_orders_channel", "channel IS NULL OR channel IN ('WEB', 'MOBILE_APP', 'MARKETPLACE')");

                            t.HasCheckConstraint("ck_orders_city", "city IS NULL OR length(city) <= 80");

                            t.HasCheckConstraint("ck_orders_country_code", "length(country_code) = 2 AND country_code NOT GLOB '*[^A-Z]*'");

                            t.HasCheckConstraint("ck_orders_created_at_utc", "length(created_at_utc) = 24 AND substr(created_at_utc, 24, 1) = 'Z'");

                            t.HasCheckConstraint("ck_orders_currency_code", "currency_code IN ('UYU', 'BRL', 'USD')");

                            t.HasCheckConstraint("ck_orders_device_session_id", "device_session_id IS NULL OR (length(device_session_id) BETWEEN 5 AND 64 AND device_session_id GLOB 'DEV_*' AND device_session_id NOT GLOB '*[^A-Z0-9_-]*')");

                            t.HasCheckConstraint("ck_orders_merchant_id", "length(merchant_id) BETWEEN 5 AND 64 AND merchant_id GLOB 'MER_*' AND merchant_id NOT GLOB '*[^A-Z0-9_-]*'");

                            t.HasCheckConstraint("ck_orders_merchant_reference_id", "length(merchant_reference_id) BETWEEN 5 AND 64 AND merchant_reference_id GLOB 'ORD_*' AND merchant_reference_id NOT GLOB '*[^A-Z0-9_-]*'");

                            t.HasCheckConstraint("ck_orders_occurred_at_utc", "length(occurred_at_utc) = 24 AND substr(occurred_at_utc, 24, 1) = 'Z'");
                        });
                });

            modelBuilder.Entity("Salvo.Domain.Risk.RiskEvaluation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EvaluationFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluation_fingerprint");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<string>("RuleConfigVersion")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("rule_config_version");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score");

                    b.Property<string>("SignalsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("signals_json");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationFingerprint")
                        .IsUnique()
                        .HasDatabaseName("ux_risk_evaluations_local_fingerprint")
                        .HasFilter("source = 'LOCAL'");

                    b.HasIndex("OrderId", "CreatedAt")
                        .HasDatabaseName("ix_risk_evaluations_order");

                    b.ToTable("risk_evaluations", null, t =>
                        {
                            t.HasCheckConstraint("ck_risk_evaluations_created_at_utc", "length(created_at_utc) = 24 AND substr(created_at_utc, 24, 1) = 'Z'");

                            t.HasCheckConstraint("ck_risk_evaluations_fingerprint", "evaluation_fingerprint IS NULL OR (length(evaluation_fingerprint) = 64 AND evaluation_fingerprint NOT GLOB '*[^0-9a-f]*')");

                            t.HasCheckConstraint("ck_risk_evaluations_local_completeness", "source <> 'LOCAL' OR (rule_config_version IS NOT NULL AND score IS NOT NULL AND signals_json IS NOT NULL AND evaluation_fingerprint IS NOT NULL)");

                            t.HasCheckConstraint("ck_risk_evaluations_score", "score IS NULL OR (score >= 0 AND score <= 100)");

                            t.HasCheckConstraint("ck_risk_evaluations_source", "source = 'LOCAL'");

                            t.HasCheckConstraint("ck_risk_evaluations_status", "status IN ('APPROVED', 'DENIED')");
                        });
                });

            modelBuilder.Entity("Salvo.Domain.Risk.RunEvaluation", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<string>("OrderId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<string>("EvaluationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("evaluation_id");

                    b.HasKey("RunId", "OrderId")
                        .HasName("pk_run_evaluations");

                    b.HasIndex("EvaluationId")
                        .HasDatabaseName("ix_run_evaluations_evaluation");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_run_evaluations_order");

                    b.ToTable("run_evaluations", (string)null);
                });

            modelBuilder.Entity("Salvo.Domain.Risk.ScoringRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AlertsCreated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alerts_created");

                    b.Property<int>("AlertsSkippedOpen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alerts_skipped_open");

                    b.Property<int>("AlertsSkippedReviewed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("alerts_skipped_reviewed");

                    b.Property<string>("CompletedAt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<int>("EvaluationsCreated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("evaluations_created");

                    b.Property<int>("EvaluationsReused")
                        .HasColumnType("INTEGER")
                        .HasColumnName("evaluations_reused");

                    b.Property<int>("OrderCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_count");

                    b.Property<string>("RuleConfigVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("rule_config_version");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_sequence");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_scoring_runs_run_sequence");

                    b.ToTable("scoring_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_scoring_runs_alert_counts", "alerts_created >= 0 AND alerts_skipped_open >= 0 AND alerts_skipped_reviewed >= 0 AND alerts_created + alerts_skipped_open + alerts_skipped_reviewed <= order_count");

                            t.HasCheckConstraint("ck_scoring_runs_completed_at_utc", "length(completed_at_utc) = 24 AND substr(completed_at_utc, 24, 1) = 'Z' AND completed_at_utc >= started_at_utc");

                            t.HasCheckConstraint("ck_scoring_runs_counts", "order_count >= 0 AND evaluations_created >= 0 AND evaluations_reused >= 0 AND evaluations_created + evaluations_reused = order_count");

                            t.HasCheckConstraint("ck_scoring_runs_run_sequence", "run_sequence >= 1");

                            t.HasCheckConstraint("ck_scoring_runs_started_at_utc", "length(started_at_utc) = 24 AND substr(started_at_utc, 24, 1) = 'Z'");
                        });
                });

            modelBuilder.Entity("Salvo.Domain.Alerts.Alert", b =>
                {
                    b.HasOne("Salvo.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Salvo.Domain.Risk.RiskEvaluation", null)
                        .WithMany()
                        .HasForeignKey("RiskEvaluationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Salvo.Domain.Alerts.Alert", null)
                        .WithMany()
                        .HasForeignKey("SupersedesAlertId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Salvo.Domain.Alerts.AlertReview", b =>
                {
                    b.HasOne("Salvo.Domain.Alerts.Alert", null)
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Salvo.Domain.Explanations.AlertExplanation", null)
                        .WithMany()
                        .HasForeignKey("ExplanationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Salvo.Domain.Evaluation.OrderEvaluationLabel", b =>
                {
                    b.HasOne("Salvo.Domain.Orders.Order", null)
                        .WithOne()
                        .HasForeignKey("Salvo.Domain.Evaluation.OrderEvaluationLabel", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Salvo.Domain.Explanations.AlertExplanation", b =>
                {
                    b.HasOne("Salvo.Domain.Alerts.Alert", null)
                        .WithMany()
                        .HasForeignKey("RequestedFromAlertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Salvo.Domain.Risk.RiskEvaluation", null)
                        .WithMany()
                        .HasForeignKey("RiskEvaluationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Salvo.Domain.External.ExternalEvaluation", b =>
                {
                    b.HasOne("Salvo.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Salvo.Domain.Risk.RiskEvaluation", b =>
                {
                    b.HasOne("Salvo.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Salvo.Domain.Risk.RunEvaluation", b =>
                {
                    b.HasOne("Salvo.Domain.Risk.RiskEvaluation", null)
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Salvo.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Salvo.Domain.Risk.ScoringRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
