// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Salvo.Domain.Alerts;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Salvo.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class AlertEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Salvo.Domain.Alerts.Alert",
                typeof(Alert),
                baseEntityType,
                propertyCount: 10,
                foreignKeyCount: 3,
                unnamedIndexCount: 5,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(Alert).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Alert).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 36,
                providerPropertyType: typeof(string));
            id.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            id.AddAnnotation("Relational:ColumnName", "id");

            var alertPolicyVersion = runtimeEntityType.AddProperty(
                "AlertPolicyVersion",
                typeof(string),
                propertyInfo: typeof(Alert).GetProperty("AlertPolicyVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Alert).GetField("<AlertPolicyVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 32);
            alertPolicyVersion.AddAnnotation("Relational:ColumnName", "alert_policy_version");

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(Alert).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Alert).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 24,
                valueConverter: new UtcDateTimeOffsetConverter());
            createdAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000Z");
            createdAt.AddAnnotation("Relational:ColumnName", "created_at_utc");

            var orderId = runtimeEntityType.AddProperty(
                "OrderId",
                typeof(Guid),
                propertyInfo: typeof(Alert).GetProperty("OrderId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Alert).GetField("<OrderId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 36,
                providerPropertyType: typeof(string));
            orderId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            orderId.AddAnnotation("Relational:ColumnName", "order_id");

            var reviewedAt = runtimeEntityType.AddProperty(
                "ReviewedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(Alert).GetProperty("ReviewedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Alert).GetField("<ReviewedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 24,
                valueConverter: new UtcDateTimeOffsetConverter());
            reviewedAt.AddAnnotation("Relational:ColumnName", "reviewed_at_utc");

            var riskEvaluationId = runtimeEntityType.AddProperty(
                "RiskEvaluationId",
                typeof(Guid),
                propertyInfo: typeof(Alert).GetProperty("RiskEvaluationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Alert).GetField("<RiskEvaluationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 36,
                providerPropertyType: typeof(string));
            riskEvaluationId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            riskEvaluationId.AddAnnotation("Relational:ColumnName", "risk_evaluation_id");

            var riskScoreSnapshot = runtimeEntityType.AddProperty(
                "RiskScoreSnapshot",
                typeof(int),
                propertyInfo: typeof(Alert).GetProperty("RiskScoreSnapshot", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Alert).GetField("<RiskScoreSnapshot>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            riskScoreSnapshot.AddAnnotation("Relational:ColumnName", "risk_score_snapshot");

            var signalsSnapshotJson = runtimeEntityType.AddProperty(
                "SignalsSnapshotJson",
                typeof(string),
                propertyInfo: typeof(Alert).GetProperty("SignalsSnapshotJson", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Alert).GetField("<SignalsSnapshotJson>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            signalsSnapshotJson.AddAnnotation("Relational:ColumnName", "signals_snapshot_json");

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(AlertStatus),
                propertyInfo: typeof(Alert).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Alert).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                concurrencyToken: true,
                maxLength: 14,
                valueConverter: new AlertStatusConverter());
            status.SetSentinelFromProviderValue("OPEN");
            status.AddAnnotation("Relational:ColumnName", "status");

            var supersedesAlertId = runtimeEntityType.AddProperty(
                "SupersedesAlertId",
                typeof(Guid?),
                propertyInfo: typeof(Alert).GetProperty("SupersedesAlertId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Alert).GetField("<SupersedesAlertId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 36,
                providerPropertyType: typeof(string));
            supersedesAlertId.AddAnnotation("Relational:ColumnName", "supersedes_alert_id");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { orderId },
                unique: true);
            index.AddAnnotation("Relational:Filter", "status = 'OPEN'");
            index.AddAnnotation("Relational:Name", "ux_alerts_open_order");

            var index0 = runtimeEntityType.AddIndex(
                new[] { riskEvaluationId },
                unique: true);
            index0.AddAnnotation("Relational:Name", "ux_alerts_risk_evaluation");

            var index1 = runtimeEntityType.AddIndex(
                new[] { supersedesAlertId });

            var index2 = runtimeEntityType.AddIndex(
                new[] { orderId, createdAt });
            index2.AddAnnotation("Relational:Name", "ix_alerts_order_created");

            var index3 = runtimeEntityType.AddIndex(
                new[] { status, createdAt });
            index3.AddAnnotation("Relational:Name", "ix_alerts_status_created");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("OrderId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("RiskEvaluationId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey3(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("SupersedesAlertId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "alerts");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
