// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Salvo.Domain.Explanations;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Salvo.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class AlertExplanationEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Salvo.Domain.Explanations.AlertExplanation",
                typeof(AlertExplanation),
                baseEntityType,
                propertyCount: 19,
                foreignKeyCount: 2,
                unnamedIndexCount: 3,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(AlertExplanation).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertExplanation).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 36,
                providerPropertyType: typeof(string));
            id.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            id.AddAnnotation("Relational:ColumnName", "id");

            var alertPolicyVersion = runtimeEntityType.AddProperty(
                "AlertPolicyVersion",
                typeof(string),
                propertyInfo: typeof(AlertExplanation).GetProperty("AlertPolicyVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertExplanation).GetField("<AlertPolicyVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 32);
            alertPolicyVersion.AddAnnotation("Relational:ColumnName", "alert_policy_version");

            var attemptCount = runtimeEntityType.AddProperty(
                "AttemptCount",
                typeof(int),
                propertyInfo: typeof(AlertExplanation).GetProperty("AttemptCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertExplanation).GetField("<AttemptCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            attemptCount.AddAnnotation("Relational:ColumnName", "attempt_count");

            var failureCode = runtimeEntityType.AddProperty(
                "FailureCode",
                typeof(ExplanationFailureCode?),
                propertyInfo: typeof(AlertExplanation).GetProperty("FailureCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertExplanation).GetField("<FailureCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 21,
                valueConverter: new ExplanationFailureCodeConverter());
            failureCode.SetSentinelFromProviderValue("PROVIDER_UNAVAILABLE");
            failureCode.AddAnnotation("Relational:ColumnName", "failure_code");

            var failureDetail = runtimeEntityType.AddProperty(
                "FailureDetail",
                typeof(string),
                propertyInfo: typeof(AlertExplanation).GetProperty("FailureDetail", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertExplanation).GetField("<FailureDetail>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 200);
            failureDetail.AddAnnotation("Relational:ColumnName", "failure_detail");

            var inputTokens = runtimeEntityType.AddProperty(
                "InputTokens",
                typeof(int?),
                propertyInfo: typeof(AlertExplanation).GetProperty("InputTokens", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertExplanation).GetField("<InputTokens>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            inputTokens.AddAnnotation("Relational:ColumnName", "input_tokens");

            var language = runtimeEntityType.AddProperty(
                "Language",
                typeof(ExplanationLanguage),
                propertyInfo: typeof(AlertExplanation).GetProperty("Language", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertExplanation).GetField("<Language>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 2,
                valueConverter: new ExplanationLanguageConverter());
            language.SetSentinelFromProviderValue("es");
            language.AddAnnotation("Relational:ColumnName", "language");

            var outputTokens = runtimeEntityType.AddProperty(
                "OutputTokens",
                typeof(int?),
                propertyInfo: typeof(AlertExplanation).GetProperty("OutputTokens", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertExplanation).GetField("<OutputTokens>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            outputTokens.AddAnnotation("Relational:ColumnName", "output_tokens");

            var provider = runtimeEntityType.AddProperty(
                "Provider",
                typeof(ExplanationProvider),
                propertyInfo: typeof(AlertExplanation).GetProperty("Provider", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertExplanation).GetField("<Provider>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 9,
                valueConverter: new ExplanationProviderConverter());
            provider.SetSentinelFromProviderValue("MOCK");
            provider.AddAnnotation("Relational:ColumnName", "provider");

            var providerVersion = runtimeEntityType.AddProperty(
                "ProviderVersion",
                typeof(string),
                propertyInfo: typeof(AlertExplanation).GetProperty("ProviderVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertExplanation).GetField("<ProviderVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 64);
            providerVersion.AddAnnotation("Relational:ColumnName", "provider_version");

            var referencedRulesJson = runtimeEntityType.AddProperty(
                "ReferencedRulesJson",
                typeof(string),
                propertyInfo: typeof(AlertExplanation).GetProperty("ReferencedRulesJson", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertExplanation).GetField("<ReferencedRulesJson>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            referencedRulesJson.AddAnnotation("Relational:ColumnName", "referenced_rules_json");

            var requestedAt = runtimeEntityType.AddProperty(
                "RequestedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(AlertExplanation).GetProperty("RequestedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertExplanation).GetField("<RequestedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 24,
                valueConverter: new UtcDateTimeOffsetConverter());
            requestedAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000Z");
            requestedAt.AddAnnotation("Relational:ColumnName", "requested_at_utc");

            var requestedFromAlertId = runtimeEntityType.AddProperty(
                "RequestedFromAlertId",
                typeof(Guid),
                propertyInfo: typeof(AlertExplanation).GetProperty("RequestedFromAlertId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertExplanation).GetField("<RequestedFromAlertId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 36,
                providerPropertyType: typeof(string));
            requestedFromAlertId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            requestedFromAlertId.AddAnnotation("Relational:ColumnName", "requested_from_alert_id");

            var riskEvaluationId = runtimeEntityType.AddProperty(
                "RiskEvaluationId",
                typeof(Guid),
                propertyInfo: typeof(AlertExplanation).GetProperty("RiskEvaluationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertExplanation).GetField("<RiskEvaluationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 36,
                providerPropertyType: typeof(string));
            riskEvaluationId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            riskEvaluationId.AddAnnotation("Relational:ColumnName", "risk_evaluation_id");

            var rowVersion = runtimeEntityType.AddProperty(
                "RowVersion",
                typeof(long),
                propertyInfo: typeof(AlertExplanation).GetProperty("RowVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertExplanation).GetField("<RowVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                concurrencyToken: true,
                sentinel: 0L);
            rowVersion.AddAnnotation("Relational:ColumnName", "row_version");

            var settledAt = runtimeEntityType.AddProperty(
                "SettledAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(AlertExplanation).GetProperty("SettledAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertExplanation).GetField("<SettledAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 24,
                valueConverter: new UtcDateTimeOffsetConverter());
            settledAt.AddAnnotation("Relational:ColumnName", "settled_at_utc");

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(ExplanationStatus),
                propertyInfo: typeof(AlertExplanation).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertExplanation).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 7,
                valueConverter: new ExplanationStatusConverter());
            status.SetSentinelFromProviderValue("PENDING");
            status.AddAnnotation("Relational:ColumnName", "status");

            var summary = runtimeEntityType.AddProperty(
                "Summary",
                typeof(string),
                propertyInfo: typeof(AlertExplanation).GetProperty("Summary", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertExplanation).GetField("<Summary>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 1200);
            summary.AddAnnotation("Relational:ColumnName", "summary");

            var templateVersion = runtimeEntityType.AddProperty(
                "TemplateVersion",
                typeof(string),
                propertyInfo: typeof(AlertExplanation).GetProperty("TemplateVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertExplanation).GetField("<TemplateVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 32);
            templateVersion.AddAnnotation("Relational:ColumnName", "template_version");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { requestedFromAlertId });
            index.AddAnnotation("Relational:Name", "ix_alert_explanations_requested_from_alert");

            var index0 = runtimeEntityType.AddIndex(
                new[] { riskEvaluationId, provider, language },
                unique: true);
            index0.AddAnnotation("Relational:Filter", "status = 'PENDING'");
            index0.AddAnnotation("Relational:Name", "ux_alert_explanations_pending_evaluation");

            var index1 = runtimeEntityType.AddIndex(
                new[] { riskEvaluationId, provider, templateVersion, alertPolicyVersion, language },
                unique: true);
            index1.AddAnnotation("Relational:Name", "ux_alert_explanations_identity");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("RequestedFromAlertId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("RiskEvaluationId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "alert_explanations");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
