// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Salvo.Domain.Alerts;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Salvo.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class AlertReviewEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Salvo.Domain.Alerts.AlertReview",
                typeof(AlertReview),
                baseEntityType,
                propertyCount: 7,
                foreignKeyCount: 2,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(AlertReview).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertReview).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 36,
                providerPropertyType: typeof(string));
            id.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            id.AddAnnotation("Relational:ColumnName", "id");

            var alertId = runtimeEntityType.AddProperty(
                "AlertId",
                typeof(Guid),
                propertyInfo: typeof(AlertReview).GetProperty("AlertId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertReview).GetField("<AlertId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 36,
                providerPropertyType: typeof(string));
            alertId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            alertId.AddAnnotation("Relational:ColumnName", "alert_id");

            var explanationId = runtimeEntityType.AddProperty(
                "ExplanationId",
                typeof(Guid?),
                propertyInfo: typeof(AlertReview).GetProperty("ExplanationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertReview).GetField("<ExplanationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 36,
                providerPropertyType: typeof(string));
            explanationId.AddAnnotation("Relational:ColumnName", "explanation_id");

            var newStatus = runtimeEntityType.AddProperty(
                "NewStatus",
                typeof(AlertStatus),
                propertyInfo: typeof(AlertReview).GetProperty("NewStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertReview).GetField("<NewStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 14,
                valueConverter: new AlertStatusConverter());
            newStatus.SetSentinelFromProviderValue("OPEN");
            newStatus.AddAnnotation("Relational:ColumnName", "new_status");

            var note = runtimeEntityType.AddProperty(
                "Note",
                typeof(string),
                propertyInfo: typeof(AlertReview).GetProperty("Note", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertReview).GetField("<Note>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 2000);
            note.AddAnnotation("Relational:ColumnName", "note");

            var previousStatus = runtimeEntityType.AddProperty(
                "PreviousStatus",
                typeof(AlertStatus),
                propertyInfo: typeof(AlertReview).GetProperty("PreviousStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertReview).GetField("<PreviousStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 14,
                valueConverter: new AlertStatusConverter());
            previousStatus.SetSentinelFromProviderValue("OPEN");
            previousStatus.AddAnnotation("Relational:ColumnName", "previous_status");

            var reviewedAt = runtimeEntityType.AddProperty(
                "ReviewedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(AlertReview).GetProperty("ReviewedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(AlertReview).GetField("<ReviewedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 24,
                valueConverter: new UtcDateTimeOffsetConverter());
            reviewedAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000Z");
            reviewedAt.AddAnnotation("Relational:ColumnName", "reviewed_at_utc");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { alertId },
                unique: true);
            index.AddAnnotation("Relational:Name", "ux_alert_reviews_alert");

            var index0 = runtimeEntityType.AddIndex(
                new[] { explanationId });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("AlertId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ExplanationId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "alert_reviews");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
