// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Salvo.Domain.External;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Salvo.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class CallbackReceiptEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Salvo.Domain.External.CallbackReceipt",
                typeof(CallbackReceipt),
                baseEntityType,
                propertyCount: 13,
                unnamedIndexCount: 4,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(CallbackReceipt).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallbackReceipt).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 36,
                providerPropertyType: typeof(string));
            id.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            id.AddAnnotation("Relational:ColumnName", "id");

            var deduplicationKey = runtimeEntityType.AddProperty(
                "DeduplicationKey",
                typeof(string),
                propertyInfo: typeof(CallbackReceipt).GetProperty("DeduplicationKey", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallbackReceipt).GetField("<DeduplicationKey>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 512);
            deduplicationKey.AddAnnotation("Relational:ColumnName", "deduplication_key");

            var externalEvaluationId = runtimeEntityType.AddProperty(
                "ExternalEvaluationId",
                typeof(string),
                propertyInfo: typeof(CallbackReceipt).GetProperty("ExternalEvaluationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallbackReceipt).GetField("<ExternalEvaluationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 128);
            externalEvaluationId.AddAnnotation("Relational:ColumnName", "external_evaluation_id");

            var lastSeenAt = runtimeEntityType.AddProperty(
                "LastSeenAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(CallbackReceipt).GetProperty("LastSeenAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallbackReceipt).GetField("<LastSeenAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 24,
                valueConverter: new UtcDateTimeOffsetConverter());
            lastSeenAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000Z");
            lastSeenAt.AddAnnotation("Relational:ColumnName", "last_seen_at_utc");

            var processedAt = runtimeEntityType.AddProperty(
                "ProcessedAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(CallbackReceipt).GetProperty("ProcessedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallbackReceipt).GetField("<ProcessedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 24,
                valueConverter: new UtcDateTimeOffsetConverter());
            processedAt.AddAnnotation("Relational:ColumnName", "processed_at_utc");

            var provider = runtimeEntityType.AddProperty(
                "Provider",
                typeof(ExternalProvider),
                propertyInfo: typeof(CallbackReceipt).GetProperty("Provider", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallbackReceipt).GetField("<Provider>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 13,
                valueConverter: new ExternalProviderConverter());
            provider.SetSentinelFromProviderValue("EXTERNAL_MOCK");
            provider.AddAnnotation("Relational:ColumnName", "provider");

            var providerInstant = runtimeEntityType.AddProperty(
                "ProviderInstant",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(CallbackReceipt).GetProperty("ProviderInstant", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallbackReceipt).GetField("<ProviderInstant>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 24,
                valueConverter: new UtcDateTimeOffsetConverter());
            providerInstant.AddAnnotation("Relational:ColumnName", "provider_instant_utc");

            var receivedAt = runtimeEntityType.AddProperty(
                "ReceivedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(CallbackReceipt).GetProperty("ReceivedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallbackReceipt).GetField("<ReceivedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 24,
                valueConverter: new UtcDateTimeOffsetConverter());
            receivedAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000Z");
            receivedAt.AddAnnotation("Relational:ColumnName", "received_at_utc");

            var referenceId = runtimeEntityType.AddProperty(
                "ReferenceId",
                typeof(string),
                propertyInfo: typeof(CallbackReceipt).GetProperty("ReferenceId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallbackReceipt).GetField("<ReferenceId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 129);
            referenceId.AddAnnotation("Relational:ColumnName", "reference_id");

            var replayCount = runtimeEntityType.AddProperty(
                "ReplayCount",
                typeof(int),
                propertyInfo: typeof(CallbackReceipt).GetProperty("ReplayCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallbackReceipt).GetField("<ReplayCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            replayCount.AddAnnotation("Relational:ColumnName", "replay_count");

            var reportedScore = runtimeEntityType.AddProperty(
                "ReportedScore",
                typeof(int?),
                propertyInfo: typeof(CallbackReceipt).GetProperty("ReportedScore", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallbackReceipt).GetField("<ReportedScore>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            reportedScore.AddAnnotation("Relational:ColumnName", "reported_score");

            var reportedStatus = runtimeEntityType.AddProperty(
                "ReportedStatus",
                typeof(ExternalEvaluationStatus),
                propertyInfo: typeof(CallbackReceipt).GetProperty("ReportedStatus", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallbackReceipt).GetField("<ReportedStatus>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 8,
                valueConverter: new ExternalEvaluationStatusConverter());
            reportedStatus.SetSentinelFromProviderValue("PENDING");
            reportedStatus.AddAnnotation("Relational:ColumnName", "reported_status");

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(CallbackReceiptStatus),
                propertyInfo: typeof(CallbackReceipt).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(CallbackReceipt).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 11,
                valueConverter: new CallbackReceiptStatusConverter());
            status.SetSentinelFromProviderValue("APPLIED");
            status.AddAnnotation("Relational:ColumnName", "status");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { provider, deduplicationKey },
                unique: true);
            index.AddAnnotation("Relational:Name", "ux_callback_receipts_provider_key");

            var index0 = runtimeEntityType.AddIndex(
                new[] { provider, externalEvaluationId });
            index0.AddAnnotation("Relational:Name", "ix_callback_receipts_provider_identifier");

            var index1 = runtimeEntityType.AddIndex(
                new[] { provider, referenceId });
            index1.AddAnnotation("Relational:Name", "ix_callback_receipts_provider_reference");

            var index2 = runtimeEntityType.AddIndex(
                new[] { provider, status });
            index2.AddAnnotation("Relational:Name", "ix_callback_receipts_provider_status");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "callback_receipts");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
