// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Salvo.Domain.External;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Salvo.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ExternalEvaluationEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Salvo.Domain.External.ExternalEvaluation",
                typeof(ExternalEvaluation),
                baseEntityType,
                propertyCount: 14,
                foreignKeyCount: 1,
                unnamedIndexCount: 5,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(ExternalEvaluation).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ExternalEvaluation).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 36,
                providerPropertyType: typeof(string));
            id.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            id.AddAnnotation("Relational:ColumnName", "id");

            var attemptCount = runtimeEntityType.AddProperty(
                "AttemptCount",
                typeof(int),
                propertyInfo: typeof(ExternalEvaluation).GetProperty("AttemptCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ExternalEvaluation).GetField("<AttemptCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            attemptCount.AddAnnotation("Relational:ColumnName", "attempt_count");

            var errorCode = runtimeEntityType.AddProperty(
                "ErrorCode",
                typeof(ExternalEvaluationErrorCode?),
                propertyInfo: typeof(ExternalEvaluation).GetProperty("ErrorCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ExternalEvaluation).GetField("<ErrorCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 17,
                valueConverter: new ExternalEvaluationErrorCodeConverter());
            errorCode.SetSentinelFromProviderValue("UNREACHABLE");
            errorCode.AddAnnotation("Relational:ColumnName", "error_code");

            var externalEvaluationId = runtimeEntityType.AddProperty(
                "ExternalEvaluationId",
                typeof(string),
                propertyInfo: typeof(ExternalEvaluation).GetProperty("ExternalEvaluationId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ExternalEvaluation).GetField("<ExternalEvaluationId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 128);
            externalEvaluationId.AddAnnotation("Relational:ColumnName", "external_evaluation_id");

            var lastErrorCode = runtimeEntityType.AddProperty(
                "LastErrorCode",
                typeof(ExternalEvaluationErrorCode?),
                propertyInfo: typeof(ExternalEvaluation).GetProperty("LastErrorCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ExternalEvaluation).GetField("<LastErrorCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 17,
                valueConverter: new ExternalEvaluationErrorCodeConverter());
            lastErrorCode.SetSentinelFromProviderValue("UNREACHABLE");
            lastErrorCode.AddAnnotation("Relational:ColumnName", "last_error_code");

            var orderId = runtimeEntityType.AddProperty(
                "OrderId",
                typeof(Guid),
                propertyInfo: typeof(ExternalEvaluation).GetProperty("OrderId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ExternalEvaluation).GetField("<OrderId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 36,
                providerPropertyType: typeof(string));
            orderId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            orderId.AddAnnotation("Relational:ColumnName", "order_id");

            var provider = runtimeEntityType.AddProperty(
                "Provider",
                typeof(ExternalProvider),
                propertyInfo: typeof(ExternalEvaluation).GetProperty("Provider", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ExternalEvaluation).GetField("<Provider>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 13,
                valueConverter: new ExternalProviderConverter());
            provider.SetSentinelFromProviderValue("EXTERNAL_MOCK");
            provider.AddAnnotation("Relational:ColumnName", "provider");

            var referenceId = runtimeEntityType.AddProperty(
                "ReferenceId",
                typeof(string),
                propertyInfo: typeof(ExternalEvaluation).GetProperty("ReferenceId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ExternalEvaluation).GetField("<ReferenceId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 129);
            referenceId.AddAnnotation("Relational:ColumnName", "reference_id");

            var requestedAt = runtimeEntityType.AddProperty(
                "RequestedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(ExternalEvaluation).GetProperty("RequestedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ExternalEvaluation).GetField("<RequestedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 24,
                valueConverter: new UtcDateTimeOffsetConverter());
            requestedAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000Z");
            requestedAt.AddAnnotation("Relational:ColumnName", "requested_at_utc");

            var score = runtimeEntityType.AddProperty(
                "Score",
                typeof(int?),
                propertyInfo: typeof(ExternalEvaluation).GetProperty("Score", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ExternalEvaluation).GetField("<Score>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            score.AddAnnotation("Relational:ColumnName", "score");

            var settledAt = runtimeEntityType.AddProperty(
                "SettledAt",
                typeof(DateTimeOffset?),
                propertyInfo: typeof(ExternalEvaluation).GetProperty("SettledAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ExternalEvaluation).GetField("<SettledAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 24,
                valueConverter: new UtcDateTimeOffsetConverter());
            settledAt.AddAnnotation("Relational:ColumnName", "settled_at_utc");

            var settledBy = runtimeEntityType.AddProperty(
                "SettledBy",
                typeof(ExternalSettlementSource?),
                propertyInfo: typeof(ExternalEvaluation).GetProperty("SettledBy", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ExternalEvaluation).GetField("<SettledBy>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 14,
                valueConverter: new ExternalSettlementSourceConverter());
            settledBy.SetSentinelFromProviderValue("SYNC");
            settledBy.AddAnnotation("Relational:ColumnName", "settled_by");

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(ExternalEvaluationStatus),
                propertyInfo: typeof(ExternalEvaluation).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ExternalEvaluation).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                concurrencyToken: true,
                maxLength: 8,
                valueConverter: new ExternalEvaluationStatusConverter());
            status.SetSentinelFromProviderValue("PENDING");
            status.AddAnnotation("Relational:ColumnName", "status");

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(ExternalEvaluation).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ExternalEvaluation).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 24,
                valueConverter: new UtcDateTimeOffsetConverter());
            updatedAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000Z");
            updatedAt.AddAnnotation("Relational:ColumnName", "updated_at_utc");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { orderId, provider },
                unique: true);
            index.AddAnnotation("Relational:Filter", "status = 'PENDING'");
            index.AddAnnotation("Relational:Name", "ux_external_evaluations_pending_order");

            var index0 = runtimeEntityType.AddIndex(
                new[] { orderId, requestedAt });
            index0.AddAnnotation("Relational:Name", "ix_external_evaluations_order_requested");

            var index1 = runtimeEntityType.AddIndex(
                new[] { provider, externalEvaluationId },
                unique: true);
            index1.AddAnnotation("Relational:Filter", "external_evaluation_id IS NOT NULL");
            index1.AddAnnotation("Relational:Name", "ux_external_evaluations_provider_identifier");

            var index2 = runtimeEntityType.AddIndex(
                new[] { provider, referenceId });
            index2.AddAnnotation("Relational:Name", "ix_external_evaluations_provider_reference");

            var index3 = runtimeEntityType.AddIndex(
                new[] { status, requestedAt });
            index3.AddAnnotation("Relational:Name", "ix_external_evaluations_status_requested");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("OrderId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "external_evaluations");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
