// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Salvo.Domain.Orders;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Salvo.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class OrderEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Salvo.Domain.Orders.Order",
                typeof(Order),
                baseEntityType,
                propertyCount: 12,
                unnamedIndexCount: 3,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(Order).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Order).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 36,
                providerPropertyType: typeof(string));
            id.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            id.AddAnnotation("Relational:ColumnName", "id");

            var amountCents = runtimeEntityType.AddProperty(
                "AmountCents",
                typeof(long),
                propertyInfo: typeof(Order).GetProperty("AmountCents", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Order).GetField("<AmountCents>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            amountCents.AddAnnotation("Relational:ColumnName", "amount_cents");

            var buyerReferenceId = runtimeEntityType.AddProperty(
                "BuyerReferenceId",
                typeof(string),
                propertyInfo: typeof(Order).GetProperty("BuyerReferenceId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Order).GetField("<BuyerReferenceId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 64);
            buyerReferenceId.AddAnnotation("Relational:ColumnName", "buyer_reference_id");

            var channel = runtimeEntityType.AddProperty(
                "Channel",
                typeof(OrderChannel?),
                propertyInfo: typeof(Order).GetProperty("Channel", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Order).GetField("<Channel>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 11,
                valueConverter: new OrderChannelConverter());
            channel.AddAnnotation("Relational:ColumnName", "channel");

            var city = runtimeEntityType.AddProperty(
                "City",
                typeof(string),
                propertyInfo: typeof(Order).GetProperty("City", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Order).GetField("<City>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 80);
            city.AddAnnotation("Relational:ColumnName", "city");

            var countryCode = runtimeEntityType.AddProperty(
                "CountryCode",
                typeof(string),
                propertyInfo: typeof(Order).GetProperty("CountryCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Order).GetField("<CountryCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 2);
            countryCode.AddAnnotation("Relational:ColumnName", "country_code");

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(Order).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Order).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 24,
                valueConverter: new UtcDateTimeOffsetConverter());
            createdAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000Z");
            createdAt.AddAnnotation("Relational:ColumnName", "created_at_utc");

            var currencyCode = runtimeEntityType.AddProperty(
                "CurrencyCode",
                typeof(string),
                propertyInfo: typeof(Order).GetProperty("CurrencyCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Order).GetField("<CurrencyCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 3);
            currencyCode.AddAnnotation("Relational:ColumnName", "currency_code");

            var deviceSessionId = runtimeEntityType.AddProperty(
                "DeviceSessionId",
                typeof(string),
                propertyInfo: typeof(Order).GetProperty("DeviceSessionId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Order).GetField("<DeviceSessionId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 64);
            deviceSessionId.AddAnnotation("Relational:ColumnName", "device_session_id");

            var merchantId = runtimeEntityType.AddProperty(
                "MerchantId",
                typeof(string),
                propertyInfo: typeof(Order).GetProperty("MerchantId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Order).GetField("<MerchantId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 64);
            merchantId.AddAnnotation("Relational:ColumnName", "merchant_id");

            var merchantReferenceId = runtimeEntityType.AddProperty(
                "MerchantReferenceId",
                typeof(string),
                propertyInfo: typeof(Order).GetProperty("MerchantReferenceId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Order).GetField("<MerchantReferenceId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 64);
            merchantReferenceId.AddAnnotation("Relational:ColumnName", "merchant_reference_id");

            var occurredAt = runtimeEntityType.AddProperty(
                "OccurredAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(Order).GetProperty("OccurredAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Order).GetField("<OccurredAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 24,
                valueConverter: new UtcDateTimeOffsetConverter());
            occurredAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000Z");
            occurredAt.AddAnnotation("Relational:ColumnName", "occurred_at_utc");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { merchantId, merchantReferenceId },
                unique: true);
            index.AddAnnotation("Relational:Name", "ux_orders_merchant_reference");

            var index0 = runtimeEntityType.AddIndex(
                new[] { occurredAt, merchantId, merchantReferenceId });
            index0.AddAnnotation("Relational:Name", "ix_orders_chronological");

            var index1 = runtimeEntityType.AddIndex(
                new[] { merchantId, buyerReferenceId, currencyCode, occurredAt, merchantReferenceId });
            index1.AddAnnotation("Relational:Name", "ix_orders_buyer_currency_history");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "orders");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
