// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Salvo.Domain.Risk;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Salvo.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class RiskEvaluationEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Salvo.Domain.Risk.RiskEvaluation",
                typeof(RiskEvaluation),
                baseEntityType,
                propertyCount: 9,
                foreignKeyCount: 1,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(RiskEvaluation).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiskEvaluation).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 36,
                providerPropertyType: typeof(string));
            id.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            id.AddAnnotation("Relational:ColumnName", "id");

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(RiskEvaluation).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiskEvaluation).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 24,
                valueConverter: new UtcDateTimeOffsetConverter());
            createdAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000Z");
            createdAt.AddAnnotation("Relational:ColumnName", "created_at_utc");

            var evaluationFingerprint = runtimeEntityType.AddProperty(
                "EvaluationFingerprint",
                typeof(string),
                propertyInfo: typeof(RiskEvaluation).GetProperty("EvaluationFingerprint", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiskEvaluation).GetField("<EvaluationFingerprint>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 64);
            evaluationFingerprint.AddAnnotation("Relational:ColumnName", "evaluation_fingerprint");

            var orderId = runtimeEntityType.AddProperty(
                "OrderId",
                typeof(Guid),
                propertyInfo: typeof(RiskEvaluation).GetProperty("OrderId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiskEvaluation).GetField("<OrderId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 36,
                providerPropertyType: typeof(string));
            orderId.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            orderId.AddAnnotation("Relational:ColumnName", "order_id");

            var ruleConfigVersion = runtimeEntityType.AddProperty(
                "RuleConfigVersion",
                typeof(string),
                propertyInfo: typeof(RiskEvaluation).GetProperty("RuleConfigVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiskEvaluation).GetField("<RuleConfigVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 32);
            ruleConfigVersion.AddAnnotation("Relational:ColumnName", "rule_config_version");

            var score = runtimeEntityType.AddProperty(
                "Score",
                typeof(int?),
                propertyInfo: typeof(RiskEvaluation).GetProperty("Score", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiskEvaluation).GetField("<Score>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            score.AddAnnotation("Relational:ColumnName", "score");

            var signalsJson = runtimeEntityType.AddProperty(
                "SignalsJson",
                typeof(string),
                propertyInfo: typeof(RiskEvaluation).GetProperty("SignalsJson", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiskEvaluation).GetField("<SignalsJson>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            signalsJson.AddAnnotation("Relational:ColumnName", "signals_json");

            var source = runtimeEntityType.AddProperty(
                "Source",
                typeof(RiskEvaluationSource),
                propertyInfo: typeof(RiskEvaluation).GetProperty("Source", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiskEvaluation).GetField("<Source>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 13,
                valueConverter: new RiskEvaluationSourceConverter());
            source.SetSentinelFromProviderValue("LOCAL");
            source.AddAnnotation("Relational:ColumnName", "source");

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(RiskEvaluationStatus),
                propertyInfo: typeof(RiskEvaluation).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(RiskEvaluation).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 8,
                valueConverter: new RiskEvaluationStatusConverter());
            status.SetSentinelFromProviderValue("APPROVED");
            status.AddAnnotation("Relational:ColumnName", "status");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { evaluationFingerprint },
                unique: true);
            index.AddAnnotation("Relational:Filter", "source = 'LOCAL'");
            index.AddAnnotation("Relational:Name", "ux_risk_evaluations_local_fingerprint");

            var index0 = runtimeEntityType.AddIndex(
                new[] { orderId, createdAt });
            index0.AddAnnotation("Relational:Name", "ix_risk_evaluations_order");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("OrderId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "risk_evaluations");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
