// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Salvo.Infrastructure.Persistence.CompiledModels
{
    public partial class SalvoDbContextModel
    {
        private SalvoDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("b8fd4319-2606-41a7-bec7-ae5b5a54caa4"), entityTypeCount: 10)
        {
        }

        partial void Initialize()
        {
            var alert = AlertEntityType.Create(this);
            var alertReview = AlertReviewEntityType.Create(this);
            var orderEvaluationLabel = OrderEvaluationLabelEntityType.Create(this);
            var alertExplanation = AlertExplanationEntityType.Create(this);
            var callbackReceipt = CallbackReceiptEntityType.Create(this);
            var externalEvaluation = ExternalEvaluationEntityType.Create(this);
            var order = OrderEntityType.Create(this);
            var riskEvaluation = RiskEvaluationEntityType.Create(this);
            var runEvaluation = RunEvaluationEntityType.Create(this);
            var scoringRun = ScoringRunEntityType.Create(this);

            AlertEntityType.CreateForeignKey1(alert, order);
            AlertEntityType.CreateForeignKey2(alert, riskEvaluation);
            AlertEntityType.CreateForeignKey3(alert, alert);
            AlertReviewEntityType.CreateForeignKey1(alertReview, alert);
            AlertReviewEntityType.CreateForeignKey2(alertReview, alertExplanation);
            OrderEvaluationLabelEntityType.CreateForeignKey1(orderEvaluationLabel, order);
            AlertExplanationEntityType.CreateForeignKey1(alertExplanation, alert);
            AlertExplanationEntityType.CreateForeignKey2(alertExplanation, riskEvaluation);
            ExternalEvaluationEntityType.CreateForeignKey1(externalEvaluation, order);
            RiskEvaluationEntityType.CreateForeignKey1(riskEvaluation, order);
            RunEvaluationEntityType.CreateForeignKey1(runEvaluation, riskEvaluation);
            RunEvaluationEntityType.CreateForeignKey2(runEvaluation, order);
            RunEvaluationEntityType.CreateForeignKey3(runEvaluation, scoringRun);

            AlertEntityType.CreateAnnotations(alert);
            AlertReviewEntityType.CreateAnnotations(alertReview);
            OrderEvaluationLabelEntityType.CreateAnnotations(orderEvaluationLabel);
            AlertExplanationEntityType.CreateAnnotations(alertExplanation);
            CallbackReceiptEntityType.CreateAnnotations(callbackReceipt);
            ExternalEvaluationEntityType.CreateAnnotations(externalEvaluation);
            OrderEntityType.CreateAnnotations(order);
            RiskEvaluationEntityType.CreateAnnotations(riskEvaluation);
            RunEvaluationEntityType.CreateAnnotations(runEvaluation);
            ScoringRunEntityType.CreateAnnotations(scoringRun);

            AddAnnotation("ProductVersion", "10.0.11");
        }
    }
}
