// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Salvo.Infrastructure.Persistence;
using Salvo.Infrastructure.Persistence.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(SalvoDbContext), typeof(SalvoDbContextModel))]
