// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Salvo.Domain.Risk;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Salvo.Infrastructure.Persistence.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class ScoringRunEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Salvo.Domain.Risk.ScoringRun",
                typeof(ScoringRun),
                baseEntityType,
                propertyCount: 11,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(ScoringRun).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ScoringRun).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 36,
                providerPropertyType: typeof(string));
            id.SetSentinelFromProviderValue("00000000-0000-0000-0000-000000000000");
            id.AddAnnotation("Relational:ColumnName", "id");

            var alertsCreated = runtimeEntityType.AddProperty(
                "AlertsCreated",
                typeof(int),
                propertyInfo: typeof(ScoringRun).GetProperty("AlertsCreated", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ScoringRun).GetField("<AlertsCreated>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            alertsCreated.AddAnnotation("Relational:ColumnName", "alerts_created");

            var alertsSkippedOpen = runtimeEntityType.AddProperty(
                "AlertsSkippedOpen",
                typeof(int),
                propertyInfo: typeof(ScoringRun).GetProperty("AlertsSkippedOpen", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ScoringRun).GetField("<AlertsSkippedOpen>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            alertsSkippedOpen.AddAnnotation("Relational:ColumnName", "alerts_skipped_open");

            var alertsSkippedReviewed = runtimeEntityType.AddProperty(
                "AlertsSkippedReviewed",
                typeof(int),
                propertyInfo: typeof(ScoringRun).GetProperty("AlertsSkippedReviewed", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ScoringRun).GetField("<AlertsSkippedReviewed>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            alertsSkippedReviewed.AddAnnotation("Relational:ColumnName", "alerts_skipped_reviewed");

            var completedAt = runtimeEntityType.AddProperty(
                "CompletedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(ScoringRun).GetProperty("CompletedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ScoringRun).GetField("<CompletedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 24,
                valueConverter: new UtcDateTimeOffsetConverter());
            completedAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000Z");
            completedAt.AddAnnotation("Relational:ColumnName", "completed_at_utc");

            var evaluationsCreated = runtimeEntityType.AddProperty(
                "EvaluationsCreated",
                typeof(int),
                propertyInfo: typeof(ScoringRun).GetProperty("EvaluationsCreated", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ScoringRun).GetField("<EvaluationsCreated>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            evaluationsCreated.AddAnnotation("Relational:ColumnName", "evaluations_created");

            var evaluationsReused = runtimeEntityType.AddProperty(
                "EvaluationsReused",
                typeof(int),
                propertyInfo: typeof(ScoringRun).GetProperty("EvaluationsReused", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ScoringRun).GetField("<EvaluationsReused>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            evaluationsReused.AddAnnotation("Relational:ColumnName", "evaluations_reused");

            var orderCount = runtimeEntityType.AddProperty(
                "OrderCount",
                typeof(int),
                propertyInfo: typeof(ScoringRun).GetProperty("OrderCount", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ScoringRun).GetField("<OrderCount>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            orderCount.AddAnnotation("Relational:ColumnName", "order_count");

            var ruleConfigVersion = runtimeEntityType.AddProperty(
                "RuleConfigVersion",
                typeof(string),
                propertyInfo: typeof(ScoringRun).GetProperty("RuleConfigVersion", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ScoringRun).GetField("<RuleConfigVersion>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 32);
            ruleConfigVersion.AddAnnotation("Relational:ColumnName", "rule_config_version");

            var sequence = runtimeEntityType.AddProperty(
                "Sequence",
                typeof(long),
                propertyInfo: typeof(ScoringRun).GetProperty("Sequence", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ScoringRun).GetField("<Sequence>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            sequence.AddAnnotation("Relational:ColumnName", "run_sequence");

            var startedAt = runtimeEntityType.AddProperty(
                "StartedAt",
                typeof(DateTimeOffset),
                propertyInfo: typeof(ScoringRun).GetProperty("StartedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(ScoringRun).GetField("<StartedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 24,
                valueConverter: new UtcDateTimeOffsetConverter());
            startedAt.SetSentinelFromProviderValue("0001-01-01T00:00:00.000Z");
            startedAt.AddAnnotation("Relational:ColumnName", "started_at_utc");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { sequence },
                unique: true);
            index.AddAnnotation("Relational:Name", "ux_scoring_runs_run_sequence");

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "scoring_runs");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
